import test from 'node:test';import assert from 'node:assert/strict';import {Blob} from 'node:buffer';import {encodeWave,inputAudioError,captureErrorMessage,capturePermissionDenied} from '../src/capture-audio.js';import {createCaptureAPI} from '../audio/capture-api.mjs';import {Readable,Writable} from 'node:stream';import {mkdtemp,mkdir,writeFile,chmod,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {resolve} from 'node:path';
test('录音WAV有效头、单声道时间与PCM振幅，空录音拒绝',()=>{const bytes=encodeWave([new Float32Array([-2,-.5,0,.5,2])],22050),v=new DataView(bytes);assert.equal(Buffer.from(bytes).subarray(0,4).toString(),'RIFF');assert.equal(v.getUint32(4,true),46);assert.equal(v.getUint16(22,true),1);assert.equal(v.getUint32(24,true),22050);assert.equal(v.getUint32(40,true),10);assert.deepEqual(Array.from({length:5},(_,i)=>v.getInt16(44+i*2,true)),[-32768,-16384,0,16384,32767]);assert.throws(()=>encodeWave([],22050),/为空/);});
test('NCM扩展名或加密签名明确拒绝；普通音频仍可导入',async()=>{const file=(name,data)=>Object.assign(new Blob([data]),{name});assert.match(await inputAudioError(file('a.ncm','anything')),/NCM/);assert.match(await inputAudioError(file('wrong.mp3','CTENFDAMrest')),/NCM/);assert.equal(await inputAudioError(file('x.wav','RIFF')),null);});
test('App采集API模拟工具：列App、启动、停止、音频读取和取消；不访问真实系统音频',{skip:process.platform!=='darwin'},async()=>{const root=await mkdtemp(resolve(tmpdir(),'capture-api-'));await mkdir(resolve(root,'.cache/bin'),{recursive:true});const helper=resolve(root,'.cache/bin/audio-capture');await writeFile(helper,`#!${process.execPath}
const fs=require('fs');if(process.argv[2]==='list'){console.log(JSON.stringify({apps:[{name:'Test Player',bundleId:'test.player'}]}));}else{console.log(JSON.stringify({event:'recording'}));process.stdin.once('data',()=>{fs.writeFileSync(process.argv[4],Buffer.alloc(300));console.log(JSON.stringify({event:'done',samples:2048}));process.exit(0);});}
`);await chmod(helper,0o755);const api=createCaptureAPI(root);
 async function call(path,body={},method='GET',headers={}){const req=Readable.from([JSON.stringify(body)]);req.method=method;req.headers={host:'localhost:52999',...headers};let bytes=[],code;const res=new Writable({write(c,e,cb){bytes.push(Buffer.from(c));cb();}});res.writeHead=c=>code=c;await api.handle(req,res,new URL('http://localhost:52999'+path));const raw=Buffer.concat(bytes);return {code,value:path.endsWith('/audio')?raw:JSON.parse(raw)};}
 async function wait(id,status){for(let i=0;i<100;i++){const j=(await call('/api/capture/jobs/'+id)).value;if(j.status===status)return j;await new Promise(r=>setTimeout(r,10));}throw Error('mock采集超时');}
 try{assert.equal((await call('/api/capture/health')).value.ready,true);assert.equal((await call('/api/capture/apps',{},'POST',{'sec-fetch-site':'cross-site'})).code,403);assert.equal((await call('/api/capture/apps',{},'POST')).value.apps[0].bundleId,'test.player');assert.equal((await call('/api/capture/jobs',{bundleId:'../../path'},'POST')).code,400);const start=await call('/api/capture/jobs',{bundleId:'test.player'},'POST');assert.equal(start.code,202);await wait(start.value.id,'recording');assert.equal((await call('/api/capture/jobs',{bundleId:'test.player'},'POST')).code,400);await call('/api/capture/jobs/'+start.value.id+'/stop',{},'POST');await wait(start.value.id,'done');assert.equal((await call('/api/capture/jobs/'+start.value.id+'/audio')).value.length,300);const next=(await call('/api/capture/jobs',{bundleId:'test.player'},'POST')).value;await call('/api/capture/jobs/'+next.id,{},'DELETE');assert.equal((await call('/api/capture/jobs/'+next.id)).value.status,'cancelled');}finally{api.close();await rm(root,{recursive:true,force:true});}
});

test('macOS拒绝TCC时提供明确授权步骤；普通错误保留原文',()=>{const raw='The user declined TCCs for application, window, display capture';assert.equal(capturePermissionDenied(raw),true);assert.match(captureErrorMessage(raw),/Terminal/);assert.equal(capturePermissionDenied(captureErrorMessage(raw)),true);assert.match(captureErrorMessage(raw),/尚未开始采集/);assert.match(captureErrorMessage(raw),/不是给被播放的网易音乐授权/);assert.equal(captureErrorMessage('音频编码器失败'),'音频编码器失败');});
