import {webcrypto} from 'node:crypto';globalThis.crypto??=webcrypto;
import test from 'node:test';import assert from 'node:assert/strict';
import {transcriptionToScore} from '../src/transcription-score.js';
import {timedCharacters,correctTimedText,parseLRC,applyTimedLyrics,applySequentialLyrics} from '../src/lyric-alignment.js';
const melody=()=>transcriptionToScore({estimatedBpm:120,clipStart:90,method:'test',notes:[{midi:60,start:0,end:1,confidence:1},{midi:62,start:1,end:2,confidence:1},{midi:64,start:3,end:5,confidence:1}]},{bpm:120,key:'C'});
test('按实际时间跨小节填词、跳过休止、支持同音多字和延音拖腔，不修改旋律',()=>{const score=melody(),words=[{text:'你好',start:.1,end:.8},{text:'呀',start:1.1,end:1.6},{text:'爱',start:3.2,end:4.8}];const mapped=applyTimedLyrics(score,timedCharacters(words));assert.deepEqual(mapped.score.measures,score.measures);assert.equal(mapped.score.lyrics[0].text,'你好');assert.equal(mapped.score.lyrics[1].text,'呀');assert.equal(mapped.score.lyrics[2].text,'爱');assert.ok(mapped.score.lyrics[2].endNoteId);assert.equal(mapped.unplaced.length,0);assert.equal(score.lyrics,undefined);});
test('LRC 使用原曲时间，选取片段，支持重复时间标签，不把整首歌词塞进片段',()=>{const chars=parseLRC('[00:00.00]前奏\n[01:30.00]你好\n[01:31.00]呀\n[01:33.00]爱\n[01:35.00]下一句',{clipStart:90,duration:5});assert.equal(chars.map(c=>c.text).join(''),'你好呀爱');assert.equal(applyTimedLyrics(melody(),chars).count,4);assert.throws(()=>parseLRC('没有时间'),/LRC/);});
test('修正错字保留识别时间；明显不同或整首文本拒绝伪造对齐',()=>{const words=[{text:'我誓爱你',start:0,end:2}];const chars=correctTimedText('我是爱你',words);assert.equal(chars.map(c=>c.text).join(''),'我是爱你');assert.equal(chars[1].start,.5);assert.throws(()=>correctTimedText('春天花开',words),/差异/);assert.throws(()=>correctTimedText('整首歌曲'.repeat(20),words),/当前识别片段/);});
test('没有时间时仅初排，允许一音多字并保留其他段；远离音符的时间不硬塞',()=>{const score=melody();score.lyrics=[{noteId:score.measures[0].notes[0].id,verse:2,text:'保留'}];const mapped=applySequentialLyrics(score,'一二三四五六七八');assert.equal(mapped.count,8);assert.ok(mapped.score.lyrics.some(l=>l.text.length>1));assert.ok(mapped.score.lyrics.some(l=>l.text==='保留'));assert.equal(applyTimedLyrics(score,[{text:'外',start:20,end:21}]).unplaced[0],'外');});
