import test from 'node:test';
import assert from 'node:assert/strict';
import {demo,validate} from '../src/model.js';
import {setLyric,moveManualLyricCharacter} from '../src/lyrics.js';
import {manualLyricAnchors} from '../src/manual-lyric-anchors.js';
import {applyAcousticLyrics,applyTimedLyrics} from '../src/lyric-alignment.js';
import {render} from '../src/render.js';
function fixture(){const s=demo();const n=s.measures[0].notes[0];n.degree=1;n.sourceTime=10;n.sourceEnd=12;n.gridTimeStart=10;n.gridTimeEnd=12;setLyric(s,n.id,1,'思念');return {s,n};}
test('手工输入和逐字拖动形成录音时间锚点，不依赖旧ASR是否识别此句',()=>{const {s,n}=fixture();const before=manualLyricAnchors(s);assert.equal(before[0].text,'思念');assert.equal(before[0].manual,true);assert.ok(before[0].start>=10);moveManualLyricCharacter(s,n.id,1,1,20);const after=manualLyricAnchors(s);assert.ok(after[0].characters[1].start>before[0].characters[1].start);});
test('声学校准保留手工词及逐字位置，去掉同位置自动重复，补入其他字',()=>{const {s,n}=fixture();moveManualLyricCharacter(s,n.id,1,1,15);const a=manualLyricAnchors(s)[0];const alignment={characters:[{id:'s',text:'思',start:a.start,end:a.start+.08,status:'acoustic'},{id:'n',text:'念',start:a.end-.08,end:a.end,status:'acoustic'},{id:'x',text:'你',start:11.8,end:11.9,status:'acoustic'}]};const next=applyAcousticLyrics(s,alignment).score;assert.deepEqual(next.lyrics,s.lyrics);assert.deepEqual(next.lyricAlignment.characters.map(c=>c.text),['你']);assert.match(render(next),/思/);assert.match(render(next),/念/);assert.match(render(next),/你/);assert.deepEqual(validate(JSON.parse(JSON.stringify(next))).lyrics,s.lyrics);const twice=applyAcousticLyrics(next,alignment).score;assert.deepEqual(twice.lyrics,s.lyrics);assert.deepEqual(twice.lyricAlignment.characters,next.lyricAlignment.characters);});
test('空校准结果与重新识别时间戳都不会抹掉人工补词',()=>{const {s}=fixture();assert.deepEqual(applyAcousticLyrics(s,{characters:[]}).score.lyrics,s.lyrics);const next=applyTimedLyrics(s,[{text:'思',start:10,end:10.1},{text:'念',start:10.1,end:10.2}]).score;assert.ok(next.lyrics.some(l=>l.text==='思念'&&l.manual));});
test('手工改过和拖过的时间轴字，在新结果换ID后仍保留且不重复',()=>{const {s,n}=fixture();s.lyrics=[];s.lyricAlignment={verse:1,displayMode:'characters',characters:[{id:'old',text:'念',start:10.5,end:10.7,manual:true,placement:{noteId:n.id,offsetX:4,manual:true}}]};const next=applyAcousticLyrics(s,{characters:[{id:'new',text:'念',start:10.5,end:10.7,status:'acoustic'}]}).score;assert.equal(next.lyricAlignment.characters.length,1);assert.equal(next.lyricAlignment.characters[0].id,'old');assert.deepEqual(next.lyricAlignment.characters[0].placement,s.lyricAlignment.characters[0].placement);});
