import test from 'node:test';import assert from 'node:assert/strict';
import {note,validate} from '../src/model.js';import {harmonizeScore} from '../src/chord-harmony.js';import {relabelScore} from '../src/pitch.js';import {render} from '../src/render.js';import {createChordWorkflow} from '../src/chord-workflow.js';
const sheet=(degrees,key='C')=>({format:'jianpu-melody',version:2,title:'按谱配和弦',key,meter:[4,4],measures:[{id:'bar',repeatStart:false,repeatEnd:false,notes:degrees.map(d=>note(d,4))}],spans:[],lyrics:[]});
test('手写谱没有音频或时间戳也能配和弦，并直接渲染',()=>{const s=sheet([1,3,5,1]),next=harmonizeScore(s);assert.equal(next.chords[0].label,'C');assert.equal(next.chords[0].measureId,'bar');assert.deepEqual(next.measures,s.measures);assert.deepEqual(next.lyrics,s.lyrics);validate(next);assert.match(render(next),/>C<\/text>/);assert.equal(s.chords,undefined);});
test('读取当前修改后的音名，忽略旧录音音高与时间',()=>{const s=sheet([2,4,6,2]);s.measures[0].notes.forEach(n=>{n.pitchMidi=60;n.sourceTime=99;n.sourceEnd=100;});const next=harmonizeScore(s);assert.equal(next.chords[0].label,'Dm');assert.equal(next.chords[0].melodySupport,1);});
test('按当前调号配实际和弦，Capo设置和人工和弦保留',()=>{const s=sheet([1,3,5,1],'G');s.guitarNotation={version:1,mode:'fingering',shapeKey:'C',capo:7};const next=harmonizeScore(s);assert.equal(next.chords[0].label,'G');assert.deepEqual(next.guitarNotation,s.guitarNotation);s.chords=[{measureId:'bar',label:'Em7',source:'manual'}];assert.deepEqual(harmonizeScore(s).chords,s.chords);});
test('全休止小节不凭空配和弦；插入小节后按当前小节ID绑定',()=>{const s=sheet([0,0,0,0]);const m=sheet([2,4,6,2]).measures[0];m.id='second';s.measures.push(m);const next=harmonizeScore(s);assert.equal(next.chords.length,1);assert.equal(next.chords[0].measureId,'second');});
test('重新定Do后仍用当前谱重评，不依赖旧音频观测',()=>{const s=harmonizeScore(sheet([1,3,5,1]));const next=relabelScore(s,'G');assert.equal(next.chordConfiguration.method,'current-score-melody-v4');assert(next.chords.length);validate(next);});
test('默认按钮按当前谱配和弦，完全不发送网络请求',async()=>{let updated,text;const flow=createChordWorkflow({getScore:()=>sheet([2,4,6,2]),getContext:()=>null,applyScore:next=>updated=next,feedback:value=>text=value,fetcher:()=>assert.fail('按谱配和弦不能请求音频接口')});await flow.run();assert.equal(updated.chords[0].label,'Dm');assert.match(text,/按当前乐谱配入/);});

test('旋律允许时优先匹配完整4536，保存命中依据',()=>{const s=sheet([4]);for(const [i,d] of [5,3,6].entries()){const m=sheet([d]).measures[0];m.id='bar'+i;s.measures.push(m);}const next=harmonizeScore(s,{granularity:'measure'});assert.deepEqual(next.chords.map(c=>c.label),['F','G','Em','Am']);assert(next.chordConfiguration.progressionMatches.some(m=>m.degrees.join('')==='4536'));});
test('完整进行奖励不能覆盖明显更合适的旋律和弦',()=>{const s=sheet([4]);for(const [i,degrees] of [[5],[1,3,5,1],[6]].entries()){const m=sheet(degrees).measures[0];m.id='bar'+i;s.measures.push(m);}const next=harmonizeScore(s,{granularity:'measure'});assert.equal(next.chords.find(c=>c.measureId==='bar1').label,'C');assert(!next.chordConfiguration.progressionMatches.some(m=>m.degrees.join('')==='4536'));});
test('全休止小节分隔进行，不跨空白拼成完整4536',()=>{const s=sheet([4]);for(const [i,d] of [5,0,3,6].entries()){const m=sheet([d]).measures[0];m.id='bar'+i;s.measures.push(m);}const next=harmonizeScore(s,{granularity:'measure'});assert(!next.chordConfiguration.progressionMatches.some(m=>m.degrees.join('')==='4536'));});
test('半小节可以分别配不同和弦，按谱面时值放在不同位置',()=>{
 const s=sheet([1,3,2,4]),next=harmonizeScore(s);
 assert.equal(next.chords.length,2);assert.deepEqual(next.chords.map(c=>[c.startTick,c.endTick]),[[0,32],[32,64]]);assert.notEqual(next.chords[0].label,next.chords[1].label);
 const glyphs=[...render(next).matchAll(/<text x="([\d.]+)" y="[\d.]+" font-size="17" font-weight="600"/g)];assert.equal(glyphs.length,2);assert(Number(glyphs[1][1])>Number(glyphs[0][1]));
});
test('同和弦的两个半小节合并，整小节模式仍可选择',()=>{const s=sheet([1,3,5,1]),next=harmonizeScore(s);assert.equal(next.chords.length,1);assert.equal(next.chords[0].endTick,64);assert.equal(harmonizeScore(sheet([1,3,2,4]),{granularity:'measure'}).chords.length,1);});
test('跨越半小节的附点音按重叠时值评分，6/8边界为三个八分音符',()=>{const s=sheet([1,2]);s.measures[0].notes[0].dots=1;s.measures[0].notes[1].base=2;const next=harmonizeScore(s);assert(next.chords.length);const compound=sheet([1,3,5,2,4,6]);compound.meter=[6,8];compound.measures[0].notes.forEach(n=>n.base=8);const chords=harmonizeScore(compound).chords;assert.equal(chords.length,2);assert.equal(chords[1].startTick,24);assert.equal(chords[1].endTick,48);});
test('常规七和弦没有复杂度扣分；支持明确时可选maj7、m7、V7',()=>{for(const [degrees,label] of [[[1,3,5,7],'Cmaj7'],[[2,4,6,1],'Dm7'],[[5,7,2,4],'G7']]){const next=harmonizeScore(sheet(degrees),{granularity:'measure'});assert.equal(next.chords[0].label,label);assert.equal(next.chordConfiguration.weights.seventhPenalty,0);}});
test('极短七音经过不触发七和弦',()=>{const s=sheet([5,7,2,4]);s.measures[0].notes[3].base=16;const next=harmonizeScore(s,{granularity:'measure'});assert.equal(next.chords[0].label,'G');});
test('扩展色彩滑条实际参与编配，0禁用扩展但不禁用七和弦',()=>{const s=sheet([1,3,7,2]);const low=harmonizeScore(s,{granularity:'measure',color:0}),high=harmonizeScore(s,{granularity:'measure',color:100});assert(!low.chords.some(c=>c.extended));assert.equal(high.chords[0].label,'Cmaj9');assert.equal(high.chordConfiguration.colorReport.actual,1);assert.equal(high.chordAnalysis.color,100);assert.equal(harmonizeScore(sheet([1,3,5,7]),{granularity:'measure',color:0}).chords[0].label,'Cmaj7');assert.equal(relabelScore(high,'C').chordConfiguration.color,100);});
test('比例偏好不强凑扩展和弦，人工扩展指法不计入自动比例',()=>{const s=sheet([1,3,5,1]);const next=harmonizeScore(s,{color:100});assert.equal(next.chordConfiguration.colorReport.actual,0);s.chords=[{measureId:'bar',label:'Cmaj9',source:'manual'}];const manual=harmonizeScore(s,{color:0});assert.deepEqual(manual.chords,s.chords);assert.equal(manual.chordConfiguration.colorReport.automaticSlots,0);});
