import {webcrypto,randomUUID} from 'node:crypto';globalThis.crypto??=webcrypto;
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,copyFile,rm,readdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {resolve} from 'node:path';import {Readable,Writable} from 'node:stream';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {createProjectStore} from '../audio/project-store.mjs';import {note} from '../src/model.js';
import {createAudioAPI} from '../audio/api.mjs';
const run=promisify(execFile);
test('重启恢复中断或取消的识别状态，不把部分人声文件登记为成功产物',async()=>{
 const a=await setup();try{
  let p=await a.store.create('中断工程');p=await a.store.addSource(p.id,Readable.from([Buffer.from('original')]),'x.mp3');
  for(const savedStatus of ['running','cancelled']){
   const id=randomUUID(),folder=resolve(a.root,'.audio-jobs',id);await mkdir(folder,{recursive:true});await a.store.startRun(p.id,id,{start:0,duration:15,mode:'mixed'});await writeFile(resolve(folder,'vocals.wav'),'partial WAV');await writeFile(resolve(folder,'job.json'),JSON.stringify({id,projectId:p.id,status:savedStatus,message:'旧任务'}));
   const api=createAudioAPI(a.root,{projects:a.store}),req=Readable.from([]);req.method='GET';req.headers={host:'localhost:51999'};let raw='';const res=new Writable({write(chunk,encoding,callback){raw+=chunk;callback();}});res.writeHead=()=>{};
   await api.handle(req,res,new URL(`http://localhost:51999/api/audio/jobs/${id}`));assert.equal(JSON.parse(raw).status,savedStatus==='running'?'error':'cancelled');p=await a.store.read(p.id);assert.equal(p.runs.find(r=>r.id===id).status,savedStatus==='running'?'interrupted':'cancelled');assert.equal(p.assets.some(asset=>asset.path===`runs/${id}/vocals.wav`),false);api.close();
  }
 }finally{await a.cleanup();}
});
async function setup(){const root=await mkdtemp(resolve(tmpdir(),'jianpu-project-test-'));await mkdir(resolve(root,'audio'));await copyFile(resolve('audio/project-archive.py'),resolve(root,'audio/project-archive.py'));return {root,store:createProjectStore(root),cleanup:()=>rm(root,{recursive:true,force:true})};}
test('single-workspace regeneration checkpoints edited score before replacing it',async()=>{
 const a=await setup();try{let p=await a.store.create('原地编辑');p.score.measures[0].notes=[note(7)];p=await a.store.patch(p.id,{revision:p.revision,score:p.score});const before=structuredClone(p.score),next=structuredClone(p.score);next.measures[0].notes[0].degree=3;
 p=await a.store.patch(p.id,{revision:p.revision,score:next,archiveScore:true,scoreBasedOn:null,workspace:{transcribe:{unified:true,scoreEdited:false}}});assert.deepEqual(p.history[0].score,before);assert.deepEqual(p.score,next);
 p=await a.store.patch(p.id,{revision:p.revision,score:next,archiveScore:true});assert.equal(p.history.length,1,'duplicate save does not create duplicate checkpoint');const req=Readable.from([Buffer.from(JSON.stringify({historyId:p.history[0].id}))]);req.method='POST';req.headers={host:'localhost:51999','content-type':'application/json'};let raw='';const res=new Writable({write(chunk,encoding,cb){raw+=chunk;cb();}});res.writeHead=()=>{};await a.store.handle(req,res,new URL('http://localhost:51999/api/projects/'+p.id+'/restore'));p=JSON.parse(raw);assert.equal(p.error,undefined,raw);assert.deepEqual(p.score,before);
 }finally{await a.cleanup();}
});
test('完整工程导入导出保持音频、识别中间文件、人工谱与工作位置，换空目录和重建 store 均可恢复',async()=>{
 const a=await setup(),b=await setup();try{
  let p=await a.store.create('工程曲');const original=Buffer.from('original audio bytes');p=await a.store.addSource(p.id,Readable.from([original]),'原曲.mp3');const runId=randomUUID(),job=resolve(a.root,'job');await mkdir(job);const params={start:25,duration:15,mode:'mixed'};
  for(const [name,data] of [['clip.wav','clip bytes'],['vocals.wav','vocal bytes'],['drums.wav','drums bytes'],['bass.wav','bass bytes'],['guitar.wav','guitar bytes'],['piano.wav','piano bytes'],['other.wav','other bytes'],['stems.json',JSON.stringify({model:'htdemucs_6s',sources:['vocals','guitar','drums','bass','piano','other']})],['result.json',JSON.stringify({notes:[{midi:60,start:0,end:.5}],clipStart:25})]])await writeFile(resolve(job,name),data);
  await a.store.startRun(p.id,runId,params);p=await a.store.finishRun(p.id,runId,job,'done','完成');p=await a.store.saveLyrics(p.id,runId,{version:1,text:'我的',words:[{text:'我的',start:0,end:.5,probability:.9}]});const recognized=structuredClone(p.score);recognized.measures[0].notes=[note(1)];p=await a.store.patch(p.id,{revision:p.revision,preview:{runId,score:recognized,notation:{bpm:100}}});p=await a.store.adopt(p.id,runId);p.score.measures[0].notes[0].degree=3;p.score.lyrics=[{id:randomUUID(),noteId:p.score.measures[0].notes[0].id,verse:1,text:'我的'}];p.score.tempo=90;p=await a.store.patch(p.id,{revision:p.revision,score:p.score,workspace:{stage:'editor',editor:{active:0,zoom:75,selected:p.score.measures[0].notes[0].id},transcribe:{bpm:'100',originalTime:26,vocalTime:1}}});
  const exported=await a.store.exportPackage(p.id),bytes=await readFile(exported.path);assert.equal(bytes.subarray(0,2).toString(),'PK');await exported.cleanup();const reopened=await b.store.importPackage(Readable.from([bytes]));assert.notEqual(reopened.id,p.id);assert.deepEqual(reopened.score,p.score);assert.deepEqual(reopened.workspace,p.workspace);assert.equal(reopened.runs[0].params.start,25);assert.deepEqual(await readFile(resolve(b.store.folder(reopened.id),reopened.source.path)),original);assert.equal(await readFile(resolve(b.store.folder(reopened.id),`runs/${runId}/vocals.wav`),'utf8'),'vocal bytes');assert.equal(await readFile(resolve(b.store.folder(reopened.id),`runs/${runId}/clip.wav`),'utf8'),'clip bytes');
  assert.equal(JSON.parse(await readFile(resolve(b.store.folder(reopened.id),`runs/${runId}/lyrics.json`),'utf8')).text,'我的');
  for(const name of ['drums','bass','guitar','piano','other'])assert.equal(await readFile(resolve(b.store.folder(reopened.id),`runs/${runId}/${name}.wav`),'utf8'),name+' bytes');
  const restarted=createProjectStore(b.root);assert.deepEqual((await restarted.read(reopened.id)).score,p.score);assert.equal((await restarted.list())[0].id,reopened.id);assert.equal(await readFile(resolve(restarted.folder(reopened.id),`runs/${runId}/recognized.jpu`),'utf8').then(JSON.parse).then(s=>s.measures[0].notes[0].degree),1);
 }finally{await a.cleanup();await b.cleanup();}
});
test('版本冲突不能覆盖新编辑；重新识别和采用新版本分别保留当前主谱与历史',async()=>{
 const a=await setup();try{let p=await a.store.create('工程');const old=p.revision;const score=structuredClone(p.score);score.measures[0].notes=[note(5)];p=await a.store.patch(p.id,{revision:old,score});await assert.rejects(a.store.patch(p.id,{revision:old,score}),/版本/);assert.equal((await a.store.read(p.id)).score.measures[0].notes[0].degree,5);
  p=await a.store.addSource(p.id,Readable.from([Buffer.from('sound')]),'x.mp3');const id=randomUUID(),job=resolve(a.root,'job');await mkdir(job);for(const f of ['clip.wav','vocals.wav','result.json'])await writeFile(resolve(job,f),f==='result.json'?'{}':'wave');await a.store.startRun(p.id,id,{start:0,duration:15,mode:'solo'});p=await a.store.finishRun(p.id,id,job,'done','完成');assert.equal(p.score.measures[0].notes[0].degree,5);const preview=structuredClone(p.score);preview.measures[0].notes[0].degree=2;p=await a.store.patch(p.id,{revision:p.revision,preview:{runId:id,score:preview,notation:{}}});p=await a.store.adopt(p.id,id);assert.equal(p.score.measures[0].notes[0].degree,2);assert.equal(p.history[0].score.measures[0].notes[0].degree,5);
 }finally{await a.cleanup();}
});
test('损坏校验值、越界 ZIP 路径和不合法工作状态被拒绝且不登记半个工程',async()=>{
 const a=await setup();try{let p=await a.store.create('工程');await assert.rejects(a.store.patch(p.id,{revision:0,workspace:{editor:{range:'bad'}}}),/选区/);const exported=await a.store.exportPackage(p.id),bad=resolve(a.root,'bad.jpp');await run('python3',['-c',`import zipfile,json,sys
with zipfile.ZipFile(sys.argv[1]) as src, zipfile.ZipFile(sys.argv[2],'w') as dst:
 for n in src.namelist():
  data=src.read(n)
  if n=='manifest.json':
   m=json.loads(data);m['assets'][0]['sha256']='0'*64;data=json.dumps(m).encode()
  dst.writestr(n,data)
`,exported.path,bad]);await assert.rejects(a.store.importPackage(Readable.from([await readFile(bad)])),/校验/);await exported.cleanup();
  await run('python3',['-c',"import zipfile,sys;z=zipfile.ZipFile(sys.argv[1],'w');z.writestr('../escape','bad');z.close()",bad]);await assert.rejects(a.store.importPackage(Readable.from([await readFile(bad)])),/路径/);assert.equal((await a.store.list()).length,1);assert.equal((await readdir(resolve(a.root,'.projects'))).filter(n=>n.startsWith('.import')).length,0);
 }finally{await a.cleanup();}
});
test('Do锁定、锚点和独立分析资产跨重开与JPP归档恢复',async()=>{const a=await setup(),b=await setup();try{let p=await a.store.create('Do校准');p=await a.store.addSource(p.id,Readable.from([Buffer.from('original')]),'x.mp3');const runId=randomUUID(),job=resolve(a.root,'keyjob');await mkdir(job);for(const [name,data] of [['clip.wav','clip'],['vocals.wav','vocals'],['result.json','{"notes":[],"duration":2}']])await writeFile(resolve(job,name),data);await a.store.startRun(p.id,runId,{start:0});p=await a.store.finishRun(p.id,runId,job,'done','完成');const {relabelScore}=await import('../src/pitch.js');p.score.measures[0].notes=[note(3)];const anchor={id:randomUUID(),start:1,end:1.5,midi:64,degree:3,accidental:0,doPc:0};const score=relabelScore(p.score,'C',{status:'confirmed',locked:true,source:'manual-anchors',anchors:[anchor]});const value={version:1,revision:randomUUID(),runId,candidates:Array.from({length:24},(_,i)=>({tonicPc:i%12,mode:i<12?'major':'minor'})),sources:[],status:'suggested'};p=await a.store.patch(p.id,{revision:p.revision,score,keyAnalysis:{runId,value},workspace:{transcribe:{keyCalibration:{anchors:[anchor],analysisRevision:value.revision}}}});assert.deepEqual((await createProjectStore(a.root).read(p.id)).score.keyMap,score.keyMap);const out=await a.store.exportPackage(p.id);const imported=await b.store.importPackage(Readable.from([await readFile(out.path)]));await out.cleanup();assert.deepEqual(imported.score.keyMap,score.keyMap);assert.deepEqual(imported.workspace,p.workspace);assert.deepEqual(JSON.parse(await readFile(resolve(b.store.folder(imported.id),`runs/${runId}/key-analysis.json`))),value);}finally{await a.cleanup();await b.cleanup();}});

test('歌词声学时间与前奏候选资产独立保存，工程包重开保持正确文本',async()=>{const a=await setup();try{let p=await a.store.create('声学资产');p=await a.store.addSource(p.id,Readable.from([Buffer.from('original')]),'song.mp3');const id=randomUUID();await a.store.startRun(p.id,id,{start:0});const job=resolve(a.root,'fixture');await mkdir(job);await writeFile(resolve(job,'clip.wav'),'fixture');await writeFile(resolve(job,'vocals.wav'),'fixture');await writeFile(resolve(job,'result.json'),JSON.stringify({notes:[]}));await a.store.finishRun(p.id,id,job,'done','');const aligned={version:1,text:'常常责怪自己',characters:[{text:'常',status:'pending'}]};const intro={version:1,notes:[{start:0,end:1,midi:60,voice:'intro'}]};await a.store.saveLyrics(p.id,id,aligned,'align');await a.store.saveLyrics(p.id,id,intro,'intro');const pkg=await a.store.exportPackage(p.id);const reopened=await a.store.importPackage(Readable.from(await readFile(pkg.path)));assert.ok(reopened.assets.some(a=>a.path.endsWith('/lyrics-alignment.json')));assert.deepEqual(JSON.parse(await readFile(resolve(a.store.folder(reopened.id),`runs/${id}/lyrics-alignment.json`))),aligned);assert.deepEqual(JSON.parse(await readFile(resolve(a.store.folder(reopened.id),`runs/${id}/intro-melody.json`))),intro);await pkg.cleanup();}finally{await a.cleanup();}});
