import {webcrypto} from 'node:crypto';globalThis.crypto??=webcrypto;
import test from 'node:test';import assert from 'node:assert/strict';
import {transcriptionToScore,pitchToDegree} from '../src/transcription-score.js';import {noteMidi} from '../src/pitch.js';import {parse,used,validate} from '../src/model.js';import {render} from '../src/render.js';
const result=notes=>({notes:notes.map(([midi,start,end])=>({midi,start,end,confidence:.95,centsDeviation:5})),estimatedBpm:120,clipStart:30,method:'test',warnings:[]});
test('绝对音高和四分音符时值生成一小节，不混入多声部',()=>{const s=transcriptionToScore(result([[60,0,.5],[62,.5,1],[64,1,1.5],[65,1.5,2]]),{key:'C'});assert.equal(s.measures.length,1);assert.deepEqual(s.measures[0].notes.map(n=>[n.degree,n.base]),[[1,4],[2,4],[3,4],[4,4]]);assert.equal(used(s.measures[0]),64);assert.equal(parse(JSON.stringify(s)).transcription.clipStart,30);});
test('长音跨小节拆分并用延音线连接，保留停顿',()=>{const s=transcriptionToScore(result([[60,0,2.5],[62,3,3.5]]),{key:'C'});assert.equal(s.spans.length,1);assert.equal(s.measures[0].notes[0].base,1);assert.ok(s.measures[1].notes.some(n=>n.degree===0));assert.ok(s.measures.every(m=>used(m)===64));validate(s);});
test('半音带升号保存、渲染，不把 C# 四舍五入成 C 或 D',()=>{const s=transcriptionToScore(result([[61,0,.5],[60,.5,1]]),{key:'C'});const n=s.measures[0].notes[0];assert.equal(n.degree,1);assert.equal(n.accidental,1);assert.equal(n.pitchMidi,61);assert.match(render(s,null,-1,true),/♯/);assert.throws(()=>validate({...s,spans:[{id:'bad-tie',type:'tie',from:n.id,to:s.measures[0].notes[1].id}]}),/延音线/);assert.deepEqual(pitchToDegree(72,'C'),{degree:1,octave:1});});
test('同一拍可以有四个十六分音符，不限制一拍一个音',()=>{const s=transcriptionToScore(result([[60,0,.125],[62,.125,.25],[64,.25,.375],[65,.375,.5]]),{key:'C'});assert.ok(s.measures[0].notes.slice(0,4).every(n=>n.base===16));assert.match(render(s,null,-1,true),/beam-2/);});
test('第一音拍位可调整，用休止占位且不会改音高',()=>{const s=transcriptionToScore(result([[60,.2,.7]]),{key:'C',firstBeat:3});assert.equal(s.measures[0].notes[0].degree,0);assert.equal(s.measures[0].notes[0].base,2);assert.equal(s.measures[0].notes[1].degree,1);});
test('自动识别的简谱八度基准整体上移一组，但仍保留检测音高和原音播放位置',()=>{const input=result([[48,0,.5],[60,.5,1]]),raised=transcriptionToScore(input,{key:'C'}),legacy=transcriptionToScore(input,{key:'C',notationOctaveShift:0});const a=raised.measures[0].notes.filter(n=>n.degree),b=legacy.measures[0].notes.filter(n=>n.degree);assert.deepEqual(a.map(n=>n.octave),[0,1]);assert.deepEqual(b.map(n=>n.octave),[-1,0]);assert.equal(raised.keyMap.referenceDoMidi,48);assert.deepEqual(a.map(n=>n.pitchMidi),[48,60]);assert.deepEqual(a.map(n=>noteMidi(n,raised)),[48,60]);assert.equal(raised.transcription.notationOctaveShift,1);});
test('无可靠旋律和过长结果明确拒绝，不编造或截断音符',()=>{assert.throws(()=>transcriptionToScore(result([])),/可靠/);assert.throws(()=>transcriptionToScore(result([[60,0,5000]]),{bpm:240,key:'C'}),/1000 小节/);assert.throws(()=>transcriptionToScore(result([[60,0,1]]),{bpm:NaN}),/速度/);});

test('automatic initial score uses terminal Do instead of a fixed C and preserves actual pitches',()=>{
 const input=result([[60,0,.5],[64,.5,1],[67,1,1.5],[65,1.5,2.3],[66,2.3,2.35]]);const s=transcriptionToScore(input);
 assert.equal(s.key,'F');assert.equal(s.keyMap.source,'terminal-note-first-v1');assert.equal(s.keyMap.status,'suggested');assert.equal(s.keyMap.locked,false);assert.equal(s.transcription.doEvidence.terminal.midi,65);assert.ok(s.transcription.warnings.some(w=>w.includes('末音优先')));for(const n of s.measures.flatMap(m=>m.notes).filter(n=>n.degree))assert.equal(noteMidi(n,s),n.pitchMidi);
});
