import {webcrypto} from 'node:crypto';globalThis.crypto??=webcrypto;
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {validate,parse,insert,note,remove,change,used} from '../src/model.js';import {newScore,insertMeasureAfter,copySelection,pasteSelection,deleteMeasure,fillRests} from '../src/commands.js';import {setLyric,distributeLyrics,lyricWidth,writeInlineLyrics,moveLyricTail,relocateLyricTail} from '../src/lyrics.js';import {layout} from '../src/layout.js';import {render} from '../src/render.js';
test('新建空乐谱，补休止符并维护至少一个小节',()=>{const s=newScore('练习','G',2,1);assert.equal(s.measures[0].notes.length,0);insert(s,0,note(3,8));fillRests(s,0);assert.equal(used(s.measures[0]),32);deleteMeasure(s,0);assert.equal(s.measures.length,1);validate(s);});
test('歌词绑定音符，多段往返；删除和转成休止清理关联',()=>{const s=newScore();insert(s,0,note(3));const id=s.measures[0].notes[0].id;setLyric(s,id,1,'你');setLyric(s,id,2,'我');assert.equal(parse(JSON.stringify(s)).lyrics.length,2);change(s,0,id,{degree:0});assert.equal(s.lyrics.length,0);assert.throws(()=>setLyric(s,id,1,'字'),/音符/);});
test('连续歌词分配跳过休止和延音续音；不足音符不部分写入',()=>{const s=newScore(),a=note(3,8),b=note(3,8),r=note(0,4),c=note(5);s.measures[0].notes=[a,b,r,c];s.spans=[{id:'tie-test',type:'tie',from:a.id,to:b.id}];distributeLyrics(s,[a.id,b.id,r.id,c.id],'你 好',1);assert.deepEqual(s.lyrics.map(l=>l.noteId),[a.id,c.id]);const before=JSON.stringify(s);assert.throws(()=>distributeLyrics(s,[a.id],'你好吗',1),/只有/);assert.equal(JSON.stringify(s),before);});
test('复制粘贴重新映射音符、歌词、连线和拖腔',()=>{const s=newScore(),a=note(3,8),b=note(3,8);s.measures[0].notes=[a,b];s.spans=[{id:'tie-test',type:'tie',from:a.id,to:b.id}];setLyric(s,a.id,1,'你',b.id);const clip=copySelection(s,[a.id,b.id]),ids=pasteSelection(s,1,null,clip);assert.notEqual(ids[0],a.id);const l=s.lyrics.find(l=>l.noteId===ids[0]);assert.equal(l.endNoteId,ids[1]);validate(s);remove(s,[ids[1]]);assert.ok(!s.lyrics.find(l=>l.noteId===ids[0]).endNoteId);});
test('长歌词占位且多段在低音点下方；导出转义文字',()=>{const s=newScore(),a=note(3,16,-2),b=note(5,8);s.measures[0].notes=[a,b];setLyric(s,a.id,1,'一段较长歌词');setLyric(s,b.id,2,'<词>');const plan=layout(s),p=plan.positions.get(a.id);assert.ok(p.x-lyricWidth('一段较长歌词')/2>=plan.measures[0].x);assert.ok(p.width>=lyricWidth('一段较长歌词'));assert.equal(plan.verseCount,2);assert.ok(p.y+62>p.y+31);const svg=render(s,null,0,true);assert.match(svg,/&lt;词&gt;/);assert.doesNotMatch(svg,/data-lyric/);});
test('歌词与结尾端点删除后仍是合法文件',()=>{const s=newScore('测试','C',4,2),a=note(1),b=note(2);s.measures[0].notes=[a];s.measures[1].notes=[b];setLyric(s,a.id,1,'你',b.id);s.endings=[{id:'ending-test',number:1,fromMeasure:s.measures[0].id,toMeasure:s.measures[1].id}];deleteMeasure(s,1);assert.equal(s.endings.length,0);assert.equal(s.lyrics[0].endNoteId,undefined);validate(s);});
test('带歌词示例保留原33小节旋律与两个结尾',()=>{const s=parse(readFileSync(new URL('../SampleSheet/我如此爱你/我们的输出/我如此爱你.jpu',import.meta.url),'utf8'));assert.equal(s.measures.length,33);assert.ok(s.lyrics.length>200);assert.ok(s.lyrics.some(l=>l.verse===2));assert.ok(s.measures.every(m=>used(m)===64));assert.equal(s.endings.length,2);});

test("当前位置插入小节保持原小节、歌词和反复端点，不追加到末尾",()=>{const s=newScore("练习","C",4,3),ids=s.measures.map(m=>m.id),n=note(3);s.measures[1].notes=[n];setLyric(s,n.id,1,"你");s.endings=[{id:"end",number:1,fromMeasure:ids[1],toMeasure:ids[2]}];const index=insertMeasureAfter(s,0);assert.equal(index,1);assert.equal(s.measures[2].id,ids[1]);assert.equal(s.measures[3].id,ids[2]);assert.equal(s.measures[index].notes.length,0);assert.equal(s.lyrics[0].noteId,n.id);assert.equal(s.endings[0].fromMeasure,ids[1]);validate(s);});

test('原歌曲任意小节后插入空小节均可连续写音符，只断开受影响的延音线',()=>{const original=parse(readFileSync(new URL('../SampleSheet/我如此爱你/我们的输出/我如此爱你.jpu',import.meta.url),'utf8')),originalIds=original.measures.flatMap(m=>m.notes).map(n=>n.id);for(let i=0;i<original.measures.length;i++){const s=structuredClone(original),at=insertMeasureAfter(s,i);validate(s);for(const d of [2,3,6,3])insert(s,at,note(d));validate(s);assert.deepEqual(s.measures[at].notes.map(n=>n.degree),[2,3,6,3]);assert.deepEqual(s.measures.filter((_,mi)=>mi!==at).flatMap(m=>m.notes).map(n=>n.id),originalIds);assert.deepEqual(s.lyrics,original.lyrics);assert.deepEqual(s.spans.filter(p=>p.type==='slur'),original.spans.filter(p=>p.type==='slur'));assert.equal(s.measures.length,34);}});
test('在延音两端之间粘贴音符会断开旧延音，不阻止粘贴',()=>{const s=newScore(),a=note(3,8),b=note(3,8);s.measures[0].notes=[a,b];s.spans=[{id:'cross-tie',type:'tie',from:a.id,to:b.id}];const other=newScore();insert(other,0,note(5,8));const clip=copySelection(other,[other.measures[0].notes[0].id]);pasteSelection(s,0,a.id,clip);assert.deepEqual(s.measures[0].notes.map(n=>n.degree),[3,5,3]);assert.equal(s.spans.length,0);validate(s);});

test('谱面连续输入按音节写入，保留单字的手动位置与拖腔',()=>{const s=newScore();s.measures[0].notes=[note(1),note(2),note(3),note(4)];const [a,b,c]=s.measures[0].notes;writeInlineLyrics(s,a.id,1,'亲爱的');assert.deepEqual(s.lyrics.map(l=>l.text),['亲','爱','的']);setLyric(s,a.id,1,'你',b.id);s.lyrics.find(l=>l.noteId===a.id).offsetX=20;writeInlineLyrics(s,a.id,1,'我');assert.equal(s.lyrics.find(l=>l.noteId===a.id).endNoteId,b.id);assert.equal(s.lyrics.find(l=>l.noteId===a.id).offsetX,20);validate(s);});
test('拖动歌词使本行后续字一起移动，不影响前面的字、其他行或其他段',()=>{const s=newScore();s.measures[0].notes=[note(1),note(2),note(3),note(4)];const [a,b,c,d]=s.measures[0].notes;for(const [i,n] of [a,b,c,d].entries())setLyric(s,n.id,1,'甲乙丙丁'[i]);setLyric(s,b.id,2,'你');assert.equal(moveLyricTail(s,b.id,1,23,[a.id,b.id,c.id]),2);assert.equal(s.lyrics.find(l=>l.noteId===a.id).offsetX,undefined);assert.equal(s.lyrics.find(l=>l.noteId===c.id).offsetX,23);assert.equal(s.lyrics.find(l=>l.noteId===d.id).offsetX,undefined);assert.equal(s.lyrics.find(l=>l.verse===2).offsetX,undefined);const restored=parse(JSON.stringify(s));assert.equal(restored.lyrics.find(l=>l.noteId===b.id&&l.verse===1).offsetX,23);assert.match(render(restored,null,0,true),/class="lyric"/);validate(s);});

test('跨行移动歌词重新绑定音符，推移目标已有歌词并保留全部文字',()=>{const s=newScore('测试','C',4,2);s.measures[0].notes=[note(1),note(2),note(3)];s.measures[1].notes=[note(1,8),note(2,8),note(3,8),note(4,8),note(5,8)];const a=s.measures[0].notes,b=s.measures[1].notes;['我','真','的'].forEach((t,i)=>setLyric(s,a[i].id,1,t));setLyric(s,b[0].id,1,'爱');setLyric(s,b[1].id,1,'你');setLyric(s,b[0].id,2,'他');relocateLyricTail(s,a[0].id,1,b[0].id,a.map(n=>n.id));assert.deepEqual(b.map(n=>s.lyrics.find(l=>l.noteId===n.id&&l.verse===1)?.text),['我','真','的','爱','你']);assert.equal(s.lyrics.find(l=>l.verse===2).text,'他');validate(s);});

test('插入歌词使目标行全部后续歌词让位，包含空档后的字',()=>{const s=newScore('测试','C',4,2);s.measures[0].notes=[note(1)];s.measures[1].notes=Array.from({length:6},()=>note(2,16));const a=s.measures[0].notes[0],b=s.measures[1].notes;setLyric(s,a.id,1,'我');setLyric(s,b[0].id,1,'爱');setLyric(s,b[3].id,1,'你');relocateLyricTail(s,a.id,1,b[0].id,[a.id]);assert.deepEqual(b.map(n=>s.lyrics.find(l=>l.noteId===n.id)?.text),['我','爱','你',undefined,undefined,undefined]);validate(s);});

test('单字拖动从同音多字中提取一个字，剩余字和源行其他词不动',()=>{const s=newScore('测试','C',4,2);s.measures[0].notes=[note(1),note(2)];s.measures[1].notes=[note(3),note(4),note(5)];const a=s.measures[0].notes,b=s.measures[1].notes;setLyric(s,a[0].id,1,'我如此爱');setLyric(s,a[1].id,1,'你');setLyric(s,b[0].id,1,'真');relocateLyricTail(s,a[0].id,1,b[0].id,a.map(n=>n.id),'single',2);assert.equal(s.lyrics.find(l=>l.noteId===a[0].id).text,'我如爱');assert.equal(s.lyrics.find(l=>l.noteId===a[1].id).text,'你');assert.equal(s.lyrics.find(l=>l.noteId===b[0].id).text,'此');assert.equal(s.lyrics.find(l=>l.noteId===b[1].id).text,'真');validate(s);});
