import assert from 'node:assert/strict';import {mkdtemp,mkdir,copyFile,readFile,writeFile,rm,symlink} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {tmpdir} from 'node:os';import {Readable,Writable} from 'node:stream';
import {loadPlaywright} from './playwright-runtime.mjs';import {createProjectStore} from '../audio/project-store.mjs';import {createAudioAPI} from '../audio/api.mjs';
const {chromium}=await loadPlaywright(),root=process.cwd(),temporary=await mkdtemp(resolve(tmpdir(),'jianpu-project-browser-')),origin='http://localhost:51999';
await mkdir(resolve(temporary,'audio'));for(const file of ['transcribe.py','separate.py','rhythm.py','project-archive.py'])await copyFile(resolve(root,'audio',file),resolve(temporary,'audio',file));
await symlink(resolve(root,'.venv-audio'),resolve(temporary,'.venv-audio'));await symlink(resolve(root,'.cache'),resolve(temporary,'.cache'));
let projects=createProjectStore(temporary),audio=createAudioAPI(temporary,{projects});const browser=await chromium.launch({headless:true,channel:'chrome'}),errors=[];
class Response extends Writable{constructor(){super();this.chunks=[];this.status=200;this.headers={};}_write(chunk,encoding,callback){this.chunks.push(Buffer.from(chunk));callback();}writeHead(status,headers){this.status=status;this.headers=headers;this.headersSent=true;return this;}}
async function makeContext(){const context=await browser.newContext({viewport:{width:1440,height:1024}});await context.addInitScript(()=>{window.showSaveFilePicker=undefined;});await context.route('**/*',async route=>{
 const request=route.request(),url=new URL(request.url());if(url.origin!==origin)return route.abort();
 if(url.pathname.startsWith('/api/')){const req=Readable.from(request.postDataBuffer()?[request.postDataBuffer()]:[]);req.method=request.method();req.headers={...request.headers(),host:'localhost:51999'};const res=new Response(),done=new Promise((ok,fail)=>{res.on('finish',ok);res.on('error',fail);});if(!(await projects.handle(req,res,url)))await audio.handle(req,res,url);await done;await route.fulfill({status:res.status,headers:res.headers,body:Buffer.concat(res.chunks)});return;}
 try{const file=resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));assert.ok(file.startsWith(root+'/'));await route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.mp3':'audio/mpeg'})[extname(file)]||'application/json'});}catch{await route.fulfill({status:404,body:'Not found'});}
 });return context;}
try{
 let context=await makeContext(),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForURL(/project=/);let id=new URL(page.url()).searchParams.get('project');
 const transcribe=()=>page.frameLocator('#transcribeFrame'),editor=()=>page.frameLocator('#editorFrame');await transcribe().locator('#runtime.ready').waitFor();await transcribe().locator('#audioFile').setInputFiles(resolve(root,'audio/examples/known-melody.mp3'));await page.waitForFunction(()=>document.querySelector('#projectStatus').textContent.includes('已自动保存'));await transcribe().locator('#sourceMode').selectOption('solo');await transcribe().locator('#clipDuration').selectOption('15');await transcribe().locator('#recognize').click();await transcribe().locator('#recognizedScore:not([hidden])').waitFor({timeout:120000});await transcribe().locator('#key').selectOption('C');await transcribe().locator('#bpm').fill('120');await transcribe().locator('#bpm').dispatchEvent('change');await transcribe().locator('#edit').click();
 await page.waitForFunction(()=>document.querySelector('#editorTab').getAttribute('aria-selected')==='true');await editor().locator('#score .digit').nth(7).waitFor();assert.equal(await editor().locator('#score .digit').count(),8);
 await editor().locator('[data-mode="select"]').click();await editor().locator('#score [data-note]').first().click();await editor().locator('#degree').selectOption('7');await editor().locator('#apply').click();await editor().locator('[data-mode="lyrics"]').click();await editor().locator('#lyricEntryMode').selectOption('note');await editor().locator('#score [data-note]').first().click();await editor().locator('#lyricInput').fill('耳朵');await editor().locator('#lyricApply').click();await editor().locator('#playbackBpm').fill('90');await editor().locator('#playbackBpm').press('Tab');
 await page.waitForFunction(()=>document.querySelector('#projectStatus').textContent.includes('已自动保存'));let p;for(let attempt=0;attempt<100;attempt++){p=await projects.read(id);if(p.score.tempo===90&&p.score.lyrics?.[0]?.text==='耳朵')break;await new Promise(resolve=>setTimeout(resolve,100));}assert.equal(p.score.measures[0].notes[0].degree,7);assert.equal(p.score.lyrics[0].text,'耳朵');assert.equal(p.score.tempo,90);const runId=p.activeRunId;assert.ok(p.assets.some(a=>a.path===`runs/${runId}/vocals.wav`));assert.ok(p.assets.some(a=>a.path===`runs/${runId}/clip.wav`));
 // Returning to recognition must not overwrite the manual score.
 await page.getByRole('tab',{name:'听歌识别'}).click();await page.getByRole('tab',{name:'简谱编辑'}).click();assert.equal((await editor().locator('#score .digit').allTextContents())[0],'7');
 const [download]=await Promise.all([page.waitForEvent('download'),page.click('#projectSave')]);assert.ok(download.suggestedFilename().endsWith('.jpp'));const bundle=await readFile(await download.path());assert.equal(bundle.subarray(0,2).toString(),'PK');
 // Exercise the file-handle streaming branch without opening an operating-system dialog.
 await page.evaluate(()=>{window.packageChunks=[];window.showSaveFilePicker=async()=>({createWritable:async()=>new WritableStream({write(chunk){window.packageChunks.push(Array.from(chunk));}})});});await page.click('#projectSaveAs');await page.waitForFunction(()=>document.querySelector('#projectStatus').textContent==='已保存工程包');assert.ok(await page.evaluate(()=>window.packageChunks.reduce((sum,chunk)=>sum+chunk.length,0)>1000));
 await mkdir(resolve(root,'design/previews'),{recursive:true});await page.screenshot({path:resolve(root,'design/previews/project-workflow-editor.png')});await page.getByRole('tab',{name:'听歌识别'}).click();await page.screenshot({path:resolve(root,'design/previews/project-workflow-transcribe.png')});
 // A new browser context and freshly instantiated backend prove persistence is not localStorage-only.
 await context.close();audio.close();projects=createProjectStore(temporary);audio=createAudioAPI(temporary,{projects});context=await makeContext();page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?project='+id);await transcribe().locator('#recognizedScore:not([hidden])').waitFor();await page.getByRole('tab',{name:'简谱编辑'}).click();await editor().locator('#score .digit').nth(7).waitFor();assert.equal((await editor().locator('#score .digit').allTextContents())[0],'7');assert.equal(await editor().locator('#playbackBpm').inputValue(),'90');assert.match(await editor().locator('#score').textContent(),/耳朵/);assert.match(await editor().locator('#editorOriginal').getAttribute('src'),/api\/projects/);assert.match(await editor().locator('#editorVocal').getAttribute('src'),/vocals/);
 // Remove all working projects and task caches and the model-cache link, then open only the portable package.
 await context.close();audio.close();await rm(resolve(temporary,'.projects'),{recursive:true,force:true});await rm(resolve(temporary,'.audio-jobs'),{recursive:true,force:true});await rm(resolve(temporary,'.cache'));projects=createProjectStore(temporary);audio=createAudioAPI(temporary,{projects});context=await makeContext();page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForURL(/project=/);await page.click('#projectOpen');await page.locator('#projectFile').setInputFiles({name:'恢复工程.jpp',mimeType:'application/zip',buffer:bundle});await page.locator('#openProjectDialog').waitFor({state:'hidden'});await editor().locator('#score .digit').nth(7).waitFor();assert.equal((await editor().locator('#score .digit').allTextContents())[0],'7');assert.match(await editor().locator('#score').textContent(),/耳朵/);await page.getByRole('tab',{name:'听歌识别'}).click();await transcribe().locator('#recognizedScore:not([hidden])').waitFor();assert.match(await transcribe().locator('#vocalPlayer').getAttribute('src'),/api\/projects/);assert.equal(await transcribe().locator('#recognize').isDisabled(),true);
 const importedId=new URL(page.url()).searchParams.get('project');assert.notEqual(importedId,id);const imported=await projects.read(importedId);assert.equal(imported.score.tempo,90);assert.deepEqual(await readFile(resolve(projects.folder(importedId),imported.source.path)),await readFile(resolve(root,'audio/examples/known-melody.mp3')));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:resolve(root,'design/previews/project-workflow-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: real MP3→Python→project assets, manual notes/lyrics/BPM, two-stage preservation, complete .jpp download, browser+backend restart, import with no old jobs/model cache, recovered audio/score and mobile layout. No listening server started.');
}finally{audio.close();await browser.close();await rm(temporary,{recursive:true,force:true});}
