import assert from 'node:assert/strict';
import {mkdtemp,mkdir,copyFile,readFile,rm,symlink} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {resolve,extname} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,webcrypto} from 'node:crypto';
import {Readable,Writable} from 'node:stream';
import {createProjectStore} from '../audio/project-store.mjs';
import {createAudioAPI} from '../audio/api.mjs';
import {transcriptionToScore} from '../src/transcription-score.js';
import {loadPlaywright} from './playwright-runtime.mjs';
globalThis.crypto??=webcrypto;
const root=process.cwd(),source=process.env.STEMS_TEST_AUDIO,output=process.env.STEMS_TEST_OUTPUT;
if(!source||!output)throw Error('指定 STEMS_TEST_AUDIO（实际原曲）和 STEMS_TEST_OUTPUT（实际六声部分离结果目录）');
const temporary=await mkdtemp(resolve(tmpdir(),'jianpu-stems-browser-')),store=createProjectStore(temporary),origin='http://localhost:51999',errors=[];
await mkdir(resolve(temporary,'audio'));await copyFile(resolve(root,'audio/project-archive.py'),resolve(temporary,'audio/project-archive.py'));await symlink(resolve(root,'.venv-audio'),resolve(temporary,'.venv-audio'));await symlink(resolve(root,'.cache'),resolve(temporary,'.cache'));
const result=JSON.parse(await readFile(resolve(output,'result.json'),'utf8'));assert.equal(result.separationModel,'htdemucs_6s');assert.equal(result.stems.length,6);assert.ok(result.notes.length);
let p=await store.create('六声部实际歌曲试听'),runId=randomUUID();p=await store.addSource(p.id,createReadStream(source),'原曲.mp3');await store.startRun(p.id,runId,{start:result.clipStart,duration:result.duration,mode:'mixed',model:'htdemucs_6s'});p=await store.finishRun(p.id,runId,output,'done','完成');
const score=transcriptionToScore(result,{title:p.name,bpm:120,key:'C',meter:4,firstBeat:1});p=await store.patch(p.id,{revision:p.revision,preview:{runId,score,notation:{bpm:120,key:'C',meter:4,firstBeat:1}},workspace:{transcribe:{sourceMode:'mixed',separationModel:'htdemucs_6s',clipStart:String(result.clipStart),clipDuration:'15'}}});p=await store.adopt(p.id,runId);p=await store.patch(p.id,{revision:p.revision,workspace:{stage:'transcribe'}});
const api=createAudioAPI(temporary,{projects:store}),{chromium}=await loadPlaywright(),browser=await chromium.launch({headless:true,channel:'chrome'});
class Response extends Writable{constructor(){super();this.chunks=[];this.status=200;this.headers={};}_write(chunk,encoding,callback){this.chunks.push(Buffer.from(chunk));callback();}writeHead(status,headers){this.status=status;this.headers=headers;this.headersSent=true;}}
async function context(){const context=await browser.newContext({viewport:{width:1440,height:1024}});await context.addInitScript(()=>{window.showSaveFilePicker=undefined;});await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin)return route.abort();if(url.pathname.startsWith('/api/')){const req=Readable.from(request.postDataBuffer()?[request.postDataBuffer()]:[]);req.method=request.method();req.headers={...request.headers(),host:'localhost:51999'};const res=new Response(),done=new Promise((ok,fail)=>{res.on('finish',ok);res.on('error',fail);});if(!(await store.handle(req,res,url)))await api.handle(req,res,url);await done;return route.fulfill({status:res.status,headers:res.headers,body:Buffer.concat(res.chunks)});}try{const file=resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));assert.ok(file.startsWith(root+'/'));await route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Not found'});}});return context;}
try{
 let ctx=await context(),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?project='+p.id);const view=()=>page.frameLocator('#transcribeFrame'),editor=()=>page.frameLocator('#editorFrame');await view().locator('#stemPlayers-guitar').waitFor();assert.equal(await view().locator('#stemPlayers audio').count(),5);assert.equal(await view().locator('#separationModel').inputValue(),'htdemucs_6s');
 for(const name of ['guitar','drums','bass','piano','other']){const player=view().locator('#stemPlayers-'+name);await player.evaluate(async node=>{await node.play();});await page.waitForTimeout(160);assert.equal(await player.evaluate(node=>node.paused),false);assert.equal(await view().locator('#vocalPlayer').evaluate(node=>node.paused),true);assert.equal(await view().locator('#stemPlayers audio').evaluateAll(nodes=>nodes.filter(node=>!node.paused).length),1);assert.ok(await player.evaluate(node=>node.duration>=14.9&&node.currentTime>0));}
 await view().locator('#vocalPlayer').evaluate(async node=>{await node.play();});assert.equal(await view().locator('#stemPlayers audio').evaluateAll(nodes=>nodes.every(node=>node.paused)),true);

 // Real media time, including original-song clip offset, drives the score line.
 const onset=result.notes[0].start;
 const vocal=view().locator('#vocalPlayer'),head=view().locator('#recognizedScore .audio-score-playhead');
 await vocal.evaluate((node,time)=>{node.pause();node.currentTime=time;},onset+.02);await head.waitFor();
 const before=await head.getAttribute('transform');await vocal.evaluate(node=>node.play());await page.waitForTimeout(100);assert.notEqual(await head.getAttribute('transform'),before);
 await vocal.evaluate(node=>node.pause());await page.waitForTimeout(80);const frozen=await head.getAttribute('transform');await page.waitForTimeout(160);assert.equal(await head.getAttribute('transform'),frozen);
 const original=view().locator('#originalPlayer');await original.evaluate((node,time)=>{node.currentTime=time;},result.clipStart+onset+.02);await page.waitForTimeout(120);assert.ok(Math.abs(Number(await head.getAttribute('data-time'))-(onset+.02))<.05);
 await head.scrollIntoViewIfNeeded();await mkdir(resolve(root,'design/previews'),{recursive:true});await page.screenshot({path:resolve(root,'design/previews/audio-score-playhead.png'),fullPage:true});
 await page.getByRole('tab',{name:'简谱编辑'}).click();await editor().locator('#projectAudio summary').click();await editor().locator('#editorStems-guitar').waitFor();assert.equal(await editor().locator('#editorStems audio').count(),5);await editor().locator('#editorStems-guitar').evaluate(async node=>{await node.play();});await page.waitForTimeout(150);assert.equal(await editor().locator('#editorStems-guitar').evaluate(node=>node.paused),false);assert.equal(await editor().locator('#editorStems').evaluate(node=>getComputedStyle(node).display),'grid');

 const editorVocal=editor().locator('#editorVocal');await editorVocal.evaluate((node,time)=>{node.currentTime=time;},onset+.02);const editorHead=editor().locator('#score .audio-score-playhead');await editorHead.waitFor();assert.ok(Math.abs(Number(await editorHead.getAttribute('data-time'))-(onset+.02))<.05);
 await editorVocal.evaluate(node=>node.play());await page.waitForTimeout(100);assert.equal(await editorVocal.evaluate(node=>node.paused),false);await editorVocal.evaluate(node=>node.pause());
 await page.getByRole('tab',{name:'听歌识别'}).click();await page.waitForFunction(()=>document.querySelector('#editorFrame').contentDocument.querySelector('#editorStems-guitar').paused);assert.equal(await editor().locator('#editorStems-guitar').evaluate(node=>node.paused),true);await view().locator('#stemPlayers-guitar').evaluate(node=>{node.currentTime=2;});await page.waitForTimeout(200);
 const [download]=await Promise.all([page.waitForEvent('download'),page.click('#projectSave')]);const bytes=await readFile(await download.path());assert.ok(bytes.length>1000);await mkdir(resolve(root,'design/previews'),{recursive:true});await page.screenshot({path:resolve(root,'design/previews/six-stem-listening.png'),fullPage:true});await ctx.close();
 ctx=await context();page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?project='+p.id);await view().locator('#stemPlayers-guitar').waitFor();await page.waitForTimeout(300);assert.ok(await view().locator('#stemPlayers-guitar').evaluate(node=>Math.abs(node.currentTime-2)<.2));assert.equal(await view().locator('#stemPlayers-guitar').evaluate(node=>node.paused),true);
 const imported=await store.importPackage(Readable.from([bytes]));for(const name of result.stems)assert.deepEqual(await readFile(resolve(store.folder(imported.id),`runs/${runId}/${name}.wav`)),await readFile(resolve(output,name+'.wav')));
 await page.goto(origin+'/?project='+imported.id);await view().locator('#stemPlayers-guitar').waitFor();await view().locator('#stemPlayers-drums').evaluate(async node=>{await node.play();});assert.equal(await view().locator('#stemPlayers-drums').evaluate(node=>node.paused),false);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS: moving score cursor, pause freeze, seek, original clip offset, editor cursor, actual six-stem WAV playback, exclusive playback, editor players, stage pause, position recovery, .jpp exact-byte restoration and mobile layout; no server started.');
}finally{api.close();await browser.close();await rm(temporary,{recursive:true,force:true});}
