import assert from 'node:assert/strict';
import {mkdtemp,mkdir,copyFile,readFile,rm,symlink} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {resolve,extname} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,webcrypto} from 'node:crypto';
import {Readable,Writable} from 'node:stream';
import {createProjectStore} from '../audio/project-store.mjs';
import {createLyricsAPI} from '../audio/lyrics-api.mjs';
import {createAudioAPI} from '../audio/api.mjs';
import {transcriptionToScore} from '../src/transcription-score.js';
import {loadPlaywright} from './playwright-runtime.mjs';
globalThis.crypto??=webcrypto;
const root=process.cwd(),source=process.env.STEMS_TEST_AUDIO,output=process.env.STEMS_TEST_OUTPUT;
if(!source||!output)throw Error('指定 STEMS_TEST_AUDIO（实际原曲）和 STEMS_TEST_OUTPUT（实际六声部分离结果目录）');
const temporary=await mkdtemp(resolve(tmpdir(),'jianpu-stems-browser-')),store=createProjectStore(temporary),origin='http://localhost:51999',errors=[];
await mkdir(resolve(temporary,'audio'));await copyFile(resolve(root,'audio/project-archive.py'),resolve(temporary,'audio/project-archive.py'));await copyFile(resolve(root,'audio/lyrics-asr.py'),resolve(temporary,'audio/lyrics-asr.py'));await symlink(resolve(root,'.venv-audio'),resolve(temporary,'.venv-audio'));await symlink(resolve(root,'.cache'),resolve(temporary,'.cache'));
const result=JSON.parse(await readFile(resolve(output,'result.json'),'utf8'));assert.equal(result.separationModel,'htdemucs_6s');assert.equal(result.stems.length,6);assert.ok(result.notes.length);
let p=await store.create('六声部实际歌曲试听'),runId=randomUUID();p=await store.addSource(p.id,createReadStream(source),'原曲.mp3');await store.startRun(p.id,runId,{start:result.clipStart,duration:result.duration,mode:'mixed',model:'htdemucs_6s'});p=await store.finishRun(p.id,runId,output,'done','完成');
const score=transcriptionToScore(result,{title:p.name,bpm:120,key:'C',meter:4,firstBeat:1});p=await store.patch(p.id,{revision:p.revision,preview:{runId,score,notation:{bpm:120,key:'C',meter:4,firstBeat:1}},workspace:{transcribe:{sourceMode:'mixed',separationModel:'htdemucs_6s',clipStart:String(result.clipStart),clipDuration:'15'}}});p=await store.adopt(p.id,runId);p=await store.patch(p.id,{revision:p.revision,workspace:{stage:'transcribe'}});
const lyricsAPI=createLyricsAPI(temporary,{projects:store}),api=createAudioAPI(temporary,{projects:store}),{chromium}=await loadPlaywright(),browser=await chromium.launch({headless:true,channel:'chrome'});
class Response extends Writable{constructor(){super();this.chunks=[];this.status=200;this.headers={};}_write(chunk,encoding,callback){this.chunks.push(Buffer.from(chunk));callback();}writeHead(status,headers){this.status=status;this.headers=headers;this.headersSent=true;}}
async function context(){const context=await browser.newContext({viewport:{width:1440,height:1024}});await context.addInitScript(()=>{window.showSaveFilePicker=undefined;});await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin)return route.abort();if(url.pathname.startsWith('/api/')){const req=Readable.from(request.postDataBuffer()?[request.postDataBuffer()]:[]);req.method=request.method();req.headers={...request.headers(),host:'localhost:51999'};const res=new Response(),done=new Promise((ok,fail)=>{res.on('finish',ok);res.on('error',fail);});if(!(await store.handle(req,res,url))&&!(await lyricsAPI.handle(req,res,url)))await api.handle(req,res,url);await done;return route.fulfill({status:res.status,headers:res.headers,body:Buffer.concat(res.chunks)});}try{const file=resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));assert.ok(file.startsWith(root+'/'));await route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[extname(file)]||'application/octet-stream'});}catch{await route.fulfill({status:404,body:'Not found'});}});return context;}
try{
 let ctx=await context(),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?project='+p.id);const view=()=>page.frameLocator('#transcribeFrame'),editor=()=>page.frameLocator('#editorFrame');await view().locator('#stemPlayers-guitar').waitFor();assert.equal(await view().locator('#stemPlayers audio').count(),5);assert.equal(await view().locator('#separationModel').inputValue(),'htdemucs_6s');
 assert.equal(await view().locator('#progressPercent').textContent(),'100%');
 await view().locator('#recognizeLyricsShortcut').click();await view().locator('#lyricsProgress').waitFor();await page.waitForFunction(()=>document.querySelector('#transcribeFrame').contentDocument.querySelector('#lyricsStatus').textContent.includes('已排入'),{},{timeout:120000});assert.ok(await view().locator('#recognizedScore .lyric').count()>0);assert.match(await view().locator('#lyricsPercent').textContent(),/100%/);const asrProject=await store.read(p.id);assert.ok(asrProject.assets.some(a=>a.path.endsWith('/lyrics.json')));const asr=JSON.parse(await readFile(resolve(store.folder(p.id),`runs/${runId}/lyrics.json`),'utf8'));assert.ok(asr.words.some(w=>w.probability>=.5));
 if(!(await view().locator('#manualLyrics').evaluate(node=>node.open)))await view().locator('#manualLyrics summary').click();await view().locator('#lyricText').fill(asr.text);await view().locator('#lyricMatchMode').selectOption('timed');await view().locator('#applyPastedLyrics').click();assert.match(await view().locator('#lyricsStatus').textContent(),/已排入/);
 await view().locator('#lyricText').fill('[01:30.00]试试同音多字\n[01:35.00]下一行\n[01:44.00]结尾');await view().locator('#lyricMatchMode').selectOption('lrc');await view().locator('#applyPastedLyrics').click();assert.match(await view().locator('#lyricsStatus').textContent(),/已排入/);
 await view().locator('#lyricText').fill('同音多个字都可以');await view().locator('#lyricMatchMode').selectOption('sequential');await view().locator('#applyPastedLyrics').click();assert.match(await view().locator('#recognizedScore').textContent(),/同/);await view().locator('#applyLyricsToEditor').click();await page.waitForFunction(()=>document.querySelector('#transcribeFrame').contentDocument.querySelector('#lyricsStatus').textContent.includes('已写入'));const updated=await store.read(p.id);assert.deepEqual(updated.score.measures,score.measures);assert.equal(updated.score.lyrics.map(l=>l.text).join(''),'同音多个字都可以');
 await page.getByRole('tab',{name:'简谱编辑'}).click();assert.match(await editor().locator('#score').textContent(),/同/);await page.getByRole('tab',{name:'听歌识别'}).click();
 const [download]=await Promise.all([page.waitForEvent('download'),page.click('#projectSave')]);const bytes=await readFile(await download.path());assert.ok(bytes.length>1000);await mkdir(resolve(root,'design/previews'),{recursive:true});await page.screenshot({path:resolve(root,'design/previews/lyrics-workflow.png'),fullPage:true});await ctx.close();
 ctx=await context();page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?project='+p.id);await view().locator('#stemPlayers-guitar').waitFor();await page.waitForTimeout(300);assert.equal(await view().locator('#lyricText').inputValue(),'同音多个字都可以');assert.ok(await view().locator('#recognizedScore .lyric').count()>0);assert.equal(await view().locator('#stemPlayers-guitar').evaluate(node=>node.paused),true);
 const imported=await store.importPackage(Readable.from([bytes]));for(const name of result.stems)assert.deepEqual(await readFile(resolve(store.folder(imported.id),`runs/${runId}/${name}.wav`)),await readFile(resolve(output,name+'.wav')));
 assert.deepEqual(JSON.parse(await readFile(resolve(store.folder(imported.id),`runs/${runId}/lyrics.json`),'utf8')),asr);await page.goto(origin+'/?project='+imported.id);await view().locator('#stemPlayers-guitar').waitFor();await view().locator('#stemPlayers-drums').evaluate(async node=>{await node.play();});assert.equal(await view().locator('#stemPlayers-drums').evaluate(node=>node.paused),false);await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS: real local Chinese Whisper, progress UI, timed ASR lyrics, corrected text, LRC, sequential fallback, lyrics-only editor update preserving notes, package/browser recovery and mobile layout; no server started.');
}finally{lyricsAPI.close();api.close();await browser.close();await rm(temporary,{recursive:true,force:true});}
