import {demo,note,insert,change,validate,parse,remove,connect,used} from './model.js';
import {newScore,emptyMeasure,insertMeasureAfter,deleteMeasure,fillRests,copySelection,pasteSelection} from './commands.js';
import {setLyric,distributeLyrics,writeInlineLyrics,relocateLyricTail,lyricWidth} from './lyrics.js';
import {saveDocument,downloadFile,safeName} from './files.js';
import {render} from './render.js';import {layout} from './layout.js';
const $=id=>document.getElementById(id),songPath='/SampleSheet/我如此爱你/我们的输出/我如此爱你.jpu';
const requested=new URLSearchParams(location.search).get('score');
let draftKey='jianpu-workbench:'+(requested||'workspace'),score=newScore(),active=0,selected=null,anchor=null,range=[],undo=[],redo=[],mode='insert',insertionSide='after',clipboard=null,fileHandle=null,fileName=safeName(score.title),savedSnapshot=null,isNew=true,saving=false,zoom=100,pendingChange=null,loadGeneration=0,fileState='尚未保存',lyricTimer=null,pendingLyric=null,inlineEdit=null,inlineComposing=false,inlineClosing=false,lyricDrag=null,suppressLyricClick=false;
let recents=[];try{recents=JSON.parse(localStorage.getItem('jianpu-recent-files')||'[]');if(!Array.isArray(recents))recents=[];recents=recents.slice(0,5);}catch{}
const icons={new:'M8 3H4v18h16V7l-4-4H8 M16 3v5h4 M8 14h8 M12 10v8',open:'M3 7h7l2 3h9l-3 10H3V7 M3 7V4h7l2 3',save:'M4 3h14l3 3v15H3V3h1 M7 3v7h10V3 M7 21v-7h10v7',undo:'M8 5L3 10l5 5 M3 10h10a7 7 0 0 1 7 7',redo:'M16 5l5 5-5 5 M21 10H11a7 7 0 0 0-7 7',cursor:'M5 3l14 11-7 1-3 7-4-19',note:'M9 17V5l10-2v12 M9 5l10-2 M9 17c0 2-5 3-5 0s5-3 5 0 M19 15c0 2-5 3-5 0s5-3 5 0',down:'M5 9l7 7 7-7',up:'M5 15l7-7 7 7',plus:'M12 4v16 M4 12h16',delete:'M4 7h16 M9 7V3h6v4 M6 7l1 14h10l1-14 M10 11v6 M14 11v6'};
for(const el of document.querySelectorAll('[data-icon]'))el.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[el.dataset.icon]}"/></svg>`;
const content=()=>JSON.stringify(score),events=()=>score.measures.flatMap((m,mi)=>m.notes.map(n=>({n,mi}))),selectedIds=()=>range.length?range:selected?[selected]:[];
const pristine=()=>isNew&&score.title==='未命名乐谱'&&score.key==='C'&&score.meter[0]===4&&score.measures.length===4&&score.measures.every(m=>!m.notes.length)&&!(score.lyrics||[]).length;
const dirty=()=>content()!==savedSnapshot&&!pristine();
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function persist(){try{localStorage.setItem(draftKey,JSON.stringify({score,fileName,savedSnapshot,isNew,fileState}));$('draftState').textContent='草稿已自动保存';}catch{$('draftState').textContent='草稿保存失败';message('浏览器存储空间不足，请保存文件。',true);}}
function updateRecent(){const entry={name:fileName,score:structuredClone(score),updatedAt:Date.now()};recents=[entry,...recents.filter(r=>r.name!==fileName)].slice(0,5);try{localStorage.setItem('jianpu-recent-files',JSON.stringify(recents));}catch{message('最近文件记录无法保存；乐谱文件不受影响。',true);}drawRecents();}
function drawRecents(){const container=$('recentList');container.replaceChildren();if(!recents.length){const empty=document.createElement('span');empty.className='menu-caption';empty.textContent='暂无最近文件';container.append(empty);}for(const entry of recents){const b=document.createElement('button');b.textContent=entry.name;b.onclick=()=>guard(()=>{try{replaceDocument(validate(structuredClone(entry.score)),{name:entry.name});message('已打开最近文件的本地副本');}catch(e){message(e.message,true);}});container.append(b);}}
function syncFields(){const n=events().find(e=>e.n.id===selected)?.n;if(n&&mode!=='insert'){$('degree').value=n.degree;$('accidental').value=n.accidental||0;$('base').value=n.base;$('octave').value=n.octave;$('dots').checked=!!n.dots;$('beamBreak').checked=!!n.beamBreak;if(n.grace){$('graceDegree').value=n.grace.degree;$('graceOctave').value=n.grace.octave;$('graceBase').value=n.grace.base;}}syncLyricInput();}
function syncLyricInput(){const n=events().find(e=>e.n.id===selected)?.n,verse=+$('lyricVerse').value;$('lyricPosition').textContent=n?`第 ${active+1} 小节 · ${n.degree?`${n.degree} 音`:'休止符'} · 第 ${verse} 段`:'点击谱面上的歌词或空格开始输入';for(const id of ['lyricApply','lyricRemove'])$(id).disabled=!n?.degree;}

function inputIndex(){const notes=score.measures[active].notes,pos=notes.findIndex(n=>n.id===selected);return pos<0?(insertionSide==='before'?0:notes.length):pos+(insertionSide==='before'?0:1);}
function focusScore(){$('score').focus({preventScroll:true});}
function draw(){
 $('score').innerHTML=render(score,selected,active,false,range,mode==='insert'?{mi:active,index:inputIndex()}:null,mode==='lyrics'?+$('lyricVerse').value:0);$('score').style.setProperty('--paper-width',`${layout(score,mode==='lyrics'?+$('lyricVerse').value:0).width*zoom/100}px`);
 $('title').value=score.title;$('key').value=score.key;$('meter').value=score.meter[0];$('documentName').textContent=(dirty()?'• ':'')+fileName;$('saveState').textContent=saving?'正在保存…':dirty()?'未保存的更改':isNew?'尚未保存':fileState;$('saveState').classList.toggle('dirty',dirty());document.title=`${dirty()?'● ':''}${score.title} · 谱间`;
 $('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('apply').disabled=!selected||mode==='insert';$('delete').disabled=!selected;$('tie').disabled=range.length!==2;$('slur').disabled=range.length<2;
 $('capacityState').textContent=`第 ${active+1} 小节 · ${used(score.measures[active])/16} / ${score.meter[0]} 拍`;$('countState').textContent=`${events().length} 个音符 / 休止`;$('selectionLabel').textContent=range.length?`已选 ${range.length} 个音符`:`第 ${active+1} 小节${selected?' · 已选音符':''}`;
 $('barCount').textContent=`${score.measures.length} 小节`;$('navTitle').textContent=score.title;$('navMeta').textContent=`1=${score.key} · ${score.meter[0]}/4`;$('notePanelTitle').textContent=mode==='insert'?'输入设置':selected?'选中音符':'输入设置';$('noteContext').textContent=mode==='insert'?'时值和八度用于后续输入；修改已有音符请点“选择”。':selected?`第 ${active+1} 小节 · 属性应用到当前音符`:'先设置时值和八度，再按数字输入。';
 $('entryHint').textContent=mode==='lyrics'?'谱面直接输入 · 拖动字，后面的字跟随':mode==='insert'?'0–7 输入 · [ ] 时值 · ↑ ↓ 八度':'点击修改 · Shift 扩选 · 数字转入写谱';
 const at=inputIndex(),count=score.measures[active].notes.length,position=at===0?'小节开头':at===count?'小节末尾':`第 ${at} 音后`;
 $('inputPosition').textContent=mode==='insert'?`输入：第 ${active+1} 小节 · ${position} · ${4/+$('base').value*($('dots').checked?1.5:1)} 拍 · ${['低两组','低一组','中音','高一组','高两组'][+$('octave').value+2]}`:mode==='lyrics'?'歌词：点击文字或虚线空格直接输入 · 拖到音符下方，原有歌词向后让位':'选择：点击音符修改属性，Shift 点击扩选';
 for(const b of document.querySelectorAll('[data-side]')){b.classList.toggle('active',b.dataset.side===insertionSide);b.setAttribute('aria-pressed',String(b.dataset.side===insertionSide));}
 for(const b of document.querySelectorAll('[data-base]'))b.classList.toggle('active',+b.dataset.base===+$('base').value);$('quickDot').classList.toggle('active',$('dots').checked);$('quickDot').setAttribute('aria-pressed',String($('dots').checked));
 for(const prop of ['repeatStart','repeatEnd','final','breakBefore'])$(prop).classList.toggle('active',!!score.measures[active][prop]);
 const list=$('barList'),navScroll=list.scrollTop;list.replaceChildren();score.measures.forEach((m,i)=>{const b=document.createElement('button');b.className=i===active?'active':'';b.title=`第 ${i+1} 小节${m.source?` · 原谱第 ${m.source.page} 页第 ${m.source.row} 行`:''}`;const number=document.createElement('span'),preview=document.createElement('span'),beats=document.createElement('span');number.className='bar-number';number.textContent=String(i+1).padStart(2,'0');preview.className='bar-preview';preview.textContent=m.notes.map(n=>n.degree).join(' ')||'空小节';beats.className='bar-beats'+(used(m)<score.meter[0]*16?' incomplete':'');beats.textContent=`${used(m)/16}拍`;b.append(number,preview,beats);b.onclick=()=>{if(!flushPendingLyric())return;active=i;selected=anchor=null;insertionSide='after';range=[];syncFields();draw();scrollToSelection();focusScore();};list.append(b);});list.scrollTop=navScroll;const current=list.children[active];if(current&&list.clientHeight){if(current.offsetTop<list.scrollTop)list.scrollTop=current.offsetTop;else if(current.offsetTop+current.offsetHeight>list.scrollTop+list.clientHeight)list.scrollTop=current.offsetTop+current.offsetHeight-list.clientHeight;}
 positionInlineEditor();
}
const state=()=>({score:structuredClone(score),active,selected,anchor,insertionSide,range:[...range]});
function restore(s){({score,active,selected,anchor,insertionSide,range}=s);}
function commit(fn,text='已更新乐谱'){const old=state();try{fn();validate(score);if(JSON.stringify(old.score)===content()){draw();return true;}undo.push(old);if(undo.length>100)undo.shift();redo=[];persist();draw();message(text);return true;}catch(e){restore(old);syncFields();draw();message(e.message,true);return false;}}
function replaceDocument(incoming,{name=safeName(incoming.title),handle=null,path=null,fresh=false}={}){clearPendingLyric();loadGeneration++;score=incoming;$('lyricBulk').value='';active=0;selected=anchor=null;insertionSide='after';range=[];undo=[];redo=[];fileHandle=handle;fileName=name;isNew=fresh;fileState=fresh?'尚未保存':'已打开';savedSnapshot=fresh?null:content();draftKey='jianpu-workbench:'+(path||'workspace');history.replaceState({},'',path?'?score='+encodeURIComponent(path):location.pathname);if(parent!==window)parent.postMessage({type:'workspace:score-path',path},location.origin);persist();syncFields();draw();$('canvasScroll').scrollTop=0;fit();if(!fresh)updateRecent();}
function guard(action){if(!flushPendingLyric())return;if(saving){message('文件正在保存，请稍候');return;}if(!dirty()){action();return;}pendingChange=action;$('unsavedDialog').showModal();}
$('unsavedCancel').onclick=()=>{pendingChange=null;$('unsavedDialog').close();};$('unsavedDiscard').onclick=()=>{const action=pendingChange;pendingChange=null;$('unsavedDialog').close();action?.();};$('unsavedSave').onclick=async()=>{const action=pendingChange;$('unsavedDialog').close();if(await save()){pendingChange=null;action?.();}else pendingChange=null;};$('unsavedDialog').addEventListener('cancel',()=>pendingChange=null);
async function save(saveAs=false){if(!flushPendingLyric())return false;if(saving)return false;saving=true;draw();const snapshot=JSON.stringify(score,null,2),snapshotCompact=content();try{const result=await saveDocument(snapshot,{handle:fileHandle,saveAs,name:saveAs||isNew?safeName(score.title):fileName.replace(/\.jianpu$/i,'.jpu')});fileHandle=result.handle;fileName=result.name;savedSnapshot=snapshotCompact;isNew=false;fileState=result.download?'已下载':'已保存';persist();updateRecent();message(result.download?`已下载 ${fileName}，请在下载目录查看`:`已保存 ${fileName}`);return true;}catch(e){if(e.name==='AbortError')message('已取消保存');else message(`保存失败：${e.message}`,true);return false;}finally{saving=false;draw();}}
$('save').onclick=()=>save();$('saveAs').onclick=()=>save(true);
$('new').onclick=()=>guard(()=>{$('newTitle').value='未命名乐谱';$('newDialog').showModal();$('newTitle').select();});$('newForm').onsubmit=e=>{e.preventDefault();try{const incoming=newScore($('newTitle').value,$('newKey').value,+$('newMeter').value,+$('newCount').value);$('newDialog').close();replaceDocument(incoming,{fresh:true});setMode('insert');message('已创建新乐谱 · 按数字键开始写谱');}catch(e){message(e.message,true);}};
$('load').onclick=()=>guard(async()=>{if(typeof window.showOpenFilePicker==='function'){try{const [handle]=await window.showOpenFilePicker({multiple:false,types:[{description:'简谱文件',accept:{'application/json':['.jpu','.jianpu','.json']}}]});const f=await handle.getFile();if(f.size>2_000_000)throw Error('文件超过 2MB');replaceDocument(parse(await f.text()),{name:f.name,handle});message(`已打开 ${f.name}`);}catch(e){if(e.name!=='AbortError')message('打开失败：'+e.message,true);}}else $('file').click();});
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>2_000_000)throw Error('文件超过 2MB');replaceDocument(parse(await f.text()),{name:f.name});message(`已打开 ${f.name}`);}catch(e){message('打开失败：'+e.message,true);}finally{$('file').value='';}};
async function loadPath(path){const generation=++loadGeneration;try{const url=new URL(path,location.href);if(url.origin!==location.origin)throw Error('只能打开本地项目文件');message('正在打开乐谱…');const response=await fetch(url);if(!response.ok)throw Error('乐谱文件无法读取');const incoming=parse(await response.text());if(generation!==loadGeneration)return;replaceDocument(incoming,{path});message(`${score.title} · ${score.measures.length} 小节`);}catch(e){message('打开失败：'+e.message,true);}}
$('song').onclick=()=>guard(()=>loadPath(songPath));for(const example of ['low','high','ornament'])$(example).onclick=()=>guard(()=>{replaceDocument(demo(example));message('已打开旋律示例');});
function setMode(next){if(!flushPendingLyric())return;mode=next;for(const b of document.querySelectorAll('[data-mode]'))b.classList.toggle('active',b.dataset.mode===mode);showPanel(mode==='lyrics');$('workspace').classList.remove('no-inspector');syncFields();draw();if(mode!=='lyrics')focusScore();else if(selected)openInlineEditor(selected,+$('lyricVerse').value);}
function showPanel(lyrics){$('lyricsPanel').hidden=!lyrics;$('propertiesPanel').hidden=lyrics;$('tabLyrics').setAttribute('aria-selected',String(lyrics));$('tabProperties').setAttribute('aria-selected',String(!lyrics));if(lyrics)syncLyricInput();}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>setMode(b.dataset.mode);$('tabLyrics').onclick=()=>setMode('lyrics');$('tabProperties').onclick=()=>{if(mode==='lyrics')mode='select';setMode(mode);};
function select(id,mi,extend=false){if(!flushPendingLyric())return;active=mi;insertionSide='after';if(extend&&anchor){const all=events().map(x=>x.n.id),a=all.indexOf(anchor),b=all.indexOf(id);range=all.slice(Math.min(a,b),Math.max(a,b)+1);}else{anchor=id;range=[];}selected=id;syncFields();draw();if(mode==='lyrics')openInlineEditor(id,+$('lyricVerse').value);else focusScore();}
function scrollToSelection(){const el=selected?$('score').querySelector(`[data-note="${CSS.escape(selected)}"]`):$('score').querySelector(`[data-measure="${active}"]`);el?.scrollIntoView({block:'nearest',inline:'nearest'});}
$('score').onclick=e=>{if(suppressLyricClick){suppressLyricClick=false;return;}const lyric=e.target.closest('[data-lyric],[data-lyric-slot]'),n=e.target.closest('[data-note]'),m=e.target.closest('[data-measure]');if(lyric){$('lyricVerse').value=lyric.dataset.verse;setMode('lyrics');select(lyric.dataset.lyric||lyric.dataset.lyricSlot,+lyric.dataset.mi,e.shiftKey);}else if(n)select(n.dataset.note,+n.dataset.mi,e.shiftKey);else if(m){flushPendingLyric();active=+m.dataset.measure;selected=anchor=null;insertionSide='after';range=[];syncFields();draw();focusScore();}};

function add(degree,half=false){if(mode!=='insert')setMode('insert');const base=+$('base').value;if(half&&base===16){message('最短支持十六分音符；请松开 Shift 输入',true);return;}
 const n=note(degree,half?base*2:base,degree?+$('octave').value:0,+$('dots').checked);if(degree&&+$('accidental').value)n.accidental=+$('accidental').value;n.beamBreak=$('beamBreak').checked;let detached=[];
 if(commit(()=>{let at=inputIndex(),m=score.measures[active];if(used(m)===score.meter[0]*16){if(at!==m.notes.length)throw Error('此处的小节已满，请先缩短或删除音符；也可在本节后插入空小节');if(active===score.measures.length-1)score.measures.push(emptyMeasure());active++;selected=null;insertionSide='before';at=0;m=score.measures[active];}
 detached=insert(score,active,n,at);selected=anchor=n.id;insertionSide='after';range=[];},'已输入音符')){message(detached.length?`已输入音符 · 已断开 ${detached.length} 条被新音符隔开的延音线（可撤销）`:'已输入音符');scrollToSelection();}focusScore();}
for(let d=0;d<=7;d++){const b=document.createElement('button');b.textContent=d;b.title=d?'输入 '+d+' 音':'输入休止符';b.onclick=()=>add(d);$('notes').append(b);}
$('apply').onclick=()=>{if(commit(()=>change(score,active,selected,{degree:+$('degree').value,accidental:+$('accidental').value,base:+$('base').value,octave:+$('octave').value,dots:+$('dots').checked,beamBreak:$('beamBreak').checked})))syncLyricInput();};
for(const b of document.querySelectorAll('[data-base]'))b.onclick=()=>{$('base').value=b.dataset.base;if(selected&&mode==='select')$('apply').click();else draw();};$('base').onchange=()=>{draw();focusScore();};$('quickDot').onclick=()=>{$('dots').checked=!$('dots').checked;if(selected&&mode==='select')$('apply').click();else draw();};
for(const [id,delta] of [['octaveDown',-1],['octaveUp',1]])$(id).onclick=()=>{$('octave').value=Math.max(-2,Math.min(2,+$('octave').value+delta));if(selected&&mode==='select')$('apply').click();else draw();};
$('delete').onclick=()=>{if(!selected)return;commit(()=>{remove(score,selectedIds());selected=anchor=null;range=[];},'已删除所选音符');syncLyricInput();};
function insertBar(){flushPendingLyric();if(commit(()=>{active=insertMeasureAfter(score,active);selected=anchor=null;insertionSide='after';range=[];},'已在当前小节后插入空小节')){setMode('insert');scrollToSelection();focusScore();}}
$('measure').onclick=insertBar;$('insertMeasure').onclick=insertBar;
$('appendMeasure').onclick=()=>{if(commit(()=>{score.measures.push(emptyMeasure());active=score.measures.length-1;selected=anchor=null;insertionSide='after';range=[];},'已在文件末尾追加小节')){setMode('insert');scrollToSelection();focusScore();}};
for(const b of document.querySelectorAll('[data-side]'))b.onclick=()=>{insertionSide=b.dataset.side;setMode('insert');};
$('deleteMeasure').onclick=()=>{commit(()=>{deleteMeasure(score,active);active=Math.min(active,score.measures.length-1);selected=anchor=null;range=[];},'已删除当前小节及关联的音符、歌词和结构端点');syncLyricInput();};$('fillRests').onclick=()=>commit(()=>fillRests(score,active),'已补齐休止符');
$('meter').onchange=()=>{const beats=+$('meter').value;commit(()=>score.meter=[beats,4]);};for(const id of ['title','key'])$(id).onchange=()=>{const value=$(id).value;commit(()=>score[id]=value);};
for(const type of ['tie','slur'])$(type).onclick=()=>commit(()=>{if(range.length<2)throw Error('先点击起音，再 Shift 点击止音');connect(score,type,range[0],range.at(-1));});$('unlink').onclick=()=>commit(()=>{const ids=selectedIds();score.spans=score.spans.filter(p=>!ids.includes(p.from)&&!ids.includes(p.to));});
$('grace').onclick=()=>commit(()=>{const n=events().find(e=>e.n.id===selected)?.n;if(!n?.degree)throw Error('请选择倚音对应的主音');change(score,active,selected,{grace:{degree:+$('graceDegree').value,octave:+$('graceOctave').value,base:+$('graceBase').value}});});$('ungrace').onclick=()=>commit(()=>{if(!selected)throw Error('请选择主音');delete score.measures[active].notes.find(n=>n.id===selected).grace;});for(const prop of ['repeatStart','repeatEnd','final','breakBefore'])$(prop).onclick=()=>commit(()=>score.measures[active][prop]=!score.measures[active][prop]);
function historyStep(from,to){if(!from.length)return;to.push(state());restore(from.pop());persist();syncFields();draw();message('已恢复编辑记录');}
$('undo').onclick=()=>historyStep(undo,redo);$('redo').onclick=()=>historyStep(redo,undo);
$('copy').onclick=()=>{try{clipboard=copySelection(score,selectedIds());message(`已复制 ${clipboard.groups.reduce((v,g)=>v+g.notes.length,0)} 个音符及歌词`);}catch(e){message(e.message,true);}};$('cut').onclick=()=>{if(!selected)return;$('copy').click();$('delete').click();};$('paste').onclick=()=>{commit(()=>{const ids=pasteSelection(score,active,selected,clipboard);selected=anchor=ids[0];range=ids;},'已粘贴音符及歌词');syncFields();};$('selectAll').onclick=()=>{range=events().map(e=>e.n.id);selected=range.at(-1)||null;anchor=range[0]||null;active=score.measures.length-1;syncFields();draw();};
function eligibleLyrics(){const tieEnds=new Set(score.spans.filter(p=>p.type==='tie').map(p=>p.to));return events().filter(e=>e.n.degree&&!tieEnds.has(e.n.id));}
function stepLyric(delta){const all=eligibleLyrics(),i=all.findIndex(e=>e.n.id===selected),next=all[Math.max(0,Math.min(all.length-1,i+delta))];if(next){select(next.n.id,next.mi);scrollToSelection();positionInlineEditor();}}
function positionInlineEditor(){if(!inlineEdit)return;const p=layout(score,inlineEdit.verse).positions.get(inlineEdit.id),svg=$('score').querySelector('svg');if(!p||!svg)return;const l=(score.lyrics||[]).find(l=>l.noteId===inlineEdit.id&&l.verse===inlineEdit.verse),point=svg.createSVGPoint();point.x=p.x+(l?.offsetX||0);point.y=p.y+62+(inlineEdit.verse-1)*26;const matrix=svg.getScreenCTM();if(!matrix)return;const xy=point.matrixTransform(matrix),box=$('canvasScroll').getBoundingClientRect(),input=$('lyricInput'),font=Math.max(14,18*matrix.a),width=Math.max(34,lyricWidth(input.value||'字')*matrix.a+16);Object.assign(input.style,{left:`${xy.x-box.left+$('canvasScroll').scrollLeft-width/2}px`,top:`${xy.y-box.top+$('canvasScroll').scrollTop-20*matrix.a-2}px`,width:`${width}px`,fontSize:`${font}px`,lineHeight:'1.1',padding:'1px 3px',height:`${Math.max(18,26*matrix.a)}px`});}
function openInlineEditor(id,verse){if(inlineEdit?.id===id&&inlineEdit.verse===verse){positionInlineEditor();$('lyricInput').focus();return;}if(!finishInlineEditor())return;const n=events().find(e=>e.n.id===id)?.n;if(!n?.degree){message('休止符下不能输入歌词',true);return;}inlineEdit={id,verse};const input=$('lyricInput');input.disabled=false;input.hidden=false;input.value=(score.lyrics||[]).find(l=>l.noteId===id&&l.verse===verse)?.text||'';positionInlineEditor();input.focus({preventScroll:true});input.select();}
function clearPendingLyric(){inlineEdit=null;inlineComposing=false;$('lyricInput').hidden=true;clearTimeout(lyricTimer);pendingLyric=null;}
function finishInlineEditor(){if(!inlineEdit||inlineClosing)return true;if(inlineComposing)return false;const edit=inlineEdit,text=$('lyricInput').value,old=(score.lyrics||[]).find(l=>l.noteId===edit.id&&l.verse===edit.verse);inlineClosing=true;inlineEdit=null;$('lyricInput').hidden=true;let result={last:edit.id,count:0};const ok=text===(old?.text||'')||commit(()=>{if($('lyricEntryMode').value==='note')setLyric(score,edit.id,edit.verse,text,old?.endNoteId);else result=writeInlineLyrics(score,edit.id,edit.verse,text);},'已在谱面写入歌词');inlineClosing=false;if(!ok){inlineEdit=edit;$('lyricVerse').value=edit.verse;$('lyricInput').hidden=false;positionInlineEditor();queueMicrotask(()=>$('lyricInput').focus());return false;}if(result.count>1){selected=anchor=result.last;active=events().find(e=>e.n.id===result.last).mi;syncFields();draw();}return true;}
function flushPendingLyric(){return finishInlineEditor();}
function applyLyric(next=false){const ok=finishInlineEditor();if(ok&&next)stepLyric(1);return ok;}
$('lyricInput').oninput=positionInlineEditor;$('lyricInput').oncompositionstart=()=>inlineComposing=true;$('lyricInput').oncompositionend=()=>{inlineComposing=false;positionInlineEditor();};
$('lyricInput').onblur=()=>{if(!inlineClosing)finishInlineEditor();};$('lyricInput').onkeydown=e=>{e.stopPropagation();if(e.isComposing||inlineComposing)return;if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();const backwards=e.shiftKey;if(finishInlineEditor())stepLyric(backwards?-1:1);}else if(e.key==='Escape'){e.preventDefault();clearPendingLyric();focusScore();}};
$('lyricApply').onclick=()=>applyLyric();$('lyricVerse').onchange=()=>{if(!finishInlineEditor())return;syncLyricInput();draw();if(selected)openInlineEditor(selected,+$('lyricVerse').value);};$('lyricPrev').onclick=()=>{if(finishInlineEditor())stepLyric(-1);};$('lyricNext').onclick=()=>{if(finishInlineEditor())stepLyric(1);};$('lyricRemove').onclick=()=>{clearPendingLyric();commit(()=>setLyric(score,selected,+$('lyricVerse').value,''),'已清除歌词');syncLyricInput();};
$('canvasScroll').addEventListener('scroll',positionInlineEditor);window.addEventListener('resize',()=>{if($('canvasScroll').clientWidth&&$('zoom').value==='fit')fit();positionInlineEditor();});
function beginLyricDrag(e){
 const group=e.target.closest('[data-lyric]'),fromEditor=e.target===$('lyricInput');if((!group&&!fromEditor)||e.button!==0)return;
 const id=fromEditor?inlineEdit?.id:group.dataset.lyric,verse=fromEditor?inlineEdit?.verse:+group.dataset.verse;if(!id||inlineComposing)return;
 let charIndex=+(e.target.closest('[data-lyric-char]')?.dataset.lyricChar||0);
 if(fromEditor){const input=$('lyricInput'),chars=Array.from(input.value),font=getComputedStyle(input),ctx=document.createElement('canvas').getContext('2d');ctx.font=`${font.fontSize} ${font.fontFamily}`;const widths=chars.map(c=>ctx.measureText(c).width),left=input.getBoundingClientRect().left+(input.getBoundingClientRect().width-widths.reduce((a,b)=>a+b,0))/2;let x=left;charIndex=Math.max(0,chars.length-1);for(let i=0;i<widths.length;i++){x+=widths[i];if(e.clientX<x){charIndex=i;break;}}}

 if(!fromEditor&&!finishInlineEditor())return;
 const plan=layout(score,verse),p=plan.positions.get(id);lyricDrag={id,verse,fromEditor,charIndex,scope:e.altKey?'single':$('lyricDragScope').value,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,rowIds:[...plan.positions.values()].filter(n=>n.row===p.row).map(n=>n.n.id),moved:false,targetId:null,preview:null};
 e.preventDefault();$('canvasScroll').setPointerCapture(e.pointerId);
}
$('canvasScroll').addEventListener('pointerdown',beginLyricDrag);
$('canvasScroll').addEventListener('dragstart',e=>{if(e.target.closest('[data-lyric],#lyricInput'))e.preventDefault();},true);
function previewLyricDrag(e,scroll=true){
 if(!lyricDrag)return;const d=lyricDrag;if(!d.moved&&Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<6)return;
 if(!d.moved&&d.fromEditor&&!finishInlineEditor()){lyricDrag=null;return;}if(!d.moved){d.matrix=$('score').querySelector('svg').getScreenCTM();d.scrollLeft=$('canvasScroll').scrollLeft;d.scrollTop=$('canvasScroll').scrollTop;}d.moved=true;e.preventDefault();
 const canvas=$('canvasScroll'),box=canvas.getBoundingClientRect();if(scroll){if(e.clientY>box.bottom-25)canvas.scrollTop+=16;else if(e.clientY<box.top+25)canvas.scrollTop-=16;}
 const svg=$('score').querySelector('svg'),matrix=d.matrix,plan=layout(score,d.verse),point=svg.createSVGPoint();point.x=e.clientX+canvas.scrollLeft-d.scrollLeft;point.y=e.clientY+canvas.scrollTop-d.scrollTop;
 const cursor=point.matrixTransform(matrix.inverse()),positions=[...plan.positions.values()].filter(p=>p.n.degree),nearestRow=positions.reduce((best,p)=>Math.abs(p.y+62+(d.verse-1)*26-cursor.y)<Math.abs(best.y+62+(d.verse-1)*26-cursor.y)?p:best).row;
 const candidate=positions.filter(p=>p.row===nearestRow).reduce((best,p)=>!best||Math.abs(p.x-cursor.x)<Math.abs(best.x-cursor.x)?p:best,null);
 if(candidate.n.id===d.targetId)return;d.targetId=candidate.n.id;
 try{
  const preview=structuredClone(score),result=relocateLyricTail(preview,d.id,d.verse,d.targetId,d.rowIds,d.scope,d.charIndex);validate(preview);d.preview=preview;d.count=result.count;d.error=null;
  $('score').innerHTML=render(preview,d.targetId,candidate.mi,false,[],null,d.verse);
  $('score').querySelector(`[data-note="${CSS.escape(d.targetId)}"]`)?.classList.add('lyric-drop-target');
  message(`第 ${candidate.mi+1} 小节 ${candidate.n.degree} 音下 · ${d.scope==='single'?'只移动这个字':'本行后续跟随'} · 原有歌词向后让位`);
 }catch(error){d.preview=null;d.error=error.message;$('score').innerHTML=render(score,selected,active,false,range,null,d.verse);message(error.message,true);}
}
$('canvasScroll').addEventListener('pointermove',previewLyricDrag);
function finishLyricDrag(e,cancel=false){
 if(!lyricDrag)return;if(!cancel&&lyricDrag.moved)previewLyricDrag(e,false);const d=lyricDrag;if(!d)return;lyricDrag=null;
 if($('canvasScroll').hasPointerCapture(e.pointerId))$('canvasScroll').releasePointerCapture(e.pointerId);
 if(d.moved){
  suppressLyricClick=true;setTimeout(()=>suppressLyricClick=false,100);
  if(!cancel&&d.preview){if(commit(()=>{score=d.preview;selected=anchor=d.targetId;active=events().find(ev=>ev.n.id===d.targetId).mi;},`已移动${d.scope==='single'?'这个字':d.count+' 个歌词音节'}，原有歌词向后让位 · 可撤销`))syncFields();}
  else{draw();if(d.error)message(d.error,true);}
 }else if(!cancel&&!d.fromEditor){suppressLyricClick=true;setTimeout(()=>suppressLyricClick=false,100);$('lyricVerse').value=d.verse;setMode('lyrics');const ev=events().find(item=>item.n.id===d.id);if(ev)select(d.id,ev.mi,e.shiftKey);}
}
$('canvasScroll').addEventListener('pointerup',e=>finishLyricDrag(e));$('canvasScroll').addEventListener('pointercancel',e=>finishLyricDrag(e,true));
$('lyricMelisma').onclick=()=>{commit(()=>{if(range.length<2)throw Error('请用 Shift 选择拖腔起止音符');const start=range[0],verse=+$('lyricVerse').value,text=(score.lyrics||[]).find(l=>l.noteId===start&&l.verse===verse)?.text;if(!text)throw Error('先给选区起音写入歌词');score.lyrics=score.lyrics.filter(l=>l.verse!==verse||l.noteId===start||!range.includes(l.noteId));setLyric(score,start,verse,text,range.at(-1));},'已设置一字多音拖腔');};
$('lyricDistribute').onclick=()=>{const all=events().map(e=>e.n.id),ids=range.length>1?range:all.slice(Math.max(0,all.indexOf(selected)));let count=0;if(commit(()=>{count=distributeLyrics(score,ids,$('lyricBulk').value,+$('lyricVerse').value);},'已分配歌词')){message(`已分配 ${count} 个歌词音节`);syncLyricInput();}};
function fit(){const width=$('canvasScroll').clientWidth-64;zoom=Math.max(20,Math.min(100,Math.floor(width/layout(score).width*100)));if(!$('zoom').querySelector('option[value="fit"]')){const option=document.createElement('option');option.value='fit';$('zoom').append(option);}$('zoom').querySelector('option[value="fit"]').textContent=`适合 · ${zoom}%`;$('zoom').value='fit';draw();}
$('fit').onclick=fit;$('zoom').onchange=()=>{if($('zoom').value==='fit')fit();else{zoom=+$('zoom').value;draw();}};$('toggleNavigator').onclick=()=>{$('workspace').classList.toggle('no-navigator');fit();};$('toggleInspector').onclick=()=>{$('workspace').classList.toggle('no-inspector');fit();};
$('svg').onclick=()=>downloadFile(render(score,null,0,true),safeName(score.title).replace(/\.jpu$/,'.svg'),'image/svg+xml');$('print').onclick=()=>{const plan=layout(score),markup=render(score,null,0,true),svg=new DOMParser().parseFromString(markup,'image/svg+xml').documentElement;let pages='';const extra=Math.max(0,plan.verseCount-1)*26;for(let r=0;r<plan.rowEnds.length;r++){const y=r===0?0:plan.baseline+(r-1)*plan.rowGap+69+extra,height=r===0?plan.baseline+69+extra:plan.rowGap;pages+=`<div class="print-row"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${y} ${plan.width} ${height}">${svg.innerHTML}</svg></div>`;}$('printSheet').innerHTML=pages;window.print();};
$('help').onclick=()=>$('helpDialog').showModal();for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>$(b.dataset.action).click();
document.addEventListener('click',e=>{for(const menu of document.querySelectorAll('.menu[open]'))if(!menu.contains(e.target)||e.target.closest('button'))menu.open=false;});
window.addEventListener('beforeunload',e=>{const completed=flushPendingLyric();if(!completed||dirty()){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{
 const typing=!!e.target.closest('textarea,input:not([type=checkbox])')||!!e.target.closest('select:not(#base):not(#octave):not(#degree)'),dialogOpen=!!document.querySelector('dialog[open]');if(e.isComposing)return;
 if((e.metaKey||e.ctrlKey)&&!dialogOpen){const key=e.key.toLowerCase();const global={s:()=>save(e.shiftKey),o:()=>$('load').click(),n:()=>$('new').click()};if(global[key]){e.preventDefault();global[key]();return;}if(typing)return;const actions={z:()=>historyStep(e.shiftKey?redo:undo,e.shiftKey?undo:redo),y:()=>$('redo').click(),c:()=>$('copy').click(),x:()=>$('cut').click(),v:()=>$('paste').click(),a:()=>$('selectAll').click()};if(actions[key]){e.preventDefault();actions[key]();}return;}
 if(typing||dialogOpen||e.altKey)return;
 const digit=/^(?:Digit|Numpad)([0-7])$/.exec(e.code)?.[1]||(/^[0-7]$/.test(e.key)?e.key:null);
 if(digit!==null&&digit!==undefined){e.preventDefault();add(+digit,e.shiftKey);return;}
 const key=e.key.toLowerCase();if(['i','v','l'].includes(key)){e.preventDefault();setMode({i:'insert',v:'select',l:'lyrics'}[key]);return;}
 if(e.key==='Enter'){if(e.target.closest('button,select,summary,a'))return;e.preventDefault();insertBar();return;}
 if(e.key==='['||e.key===']'){e.preventDefault();const values=[1,2,4,8,16],at=values.indexOf(+$('base').value),next=values[Math.max(0,Math.min(4,at+(e.key==='['?1:-1)))];document.querySelector(`[data-base="${next}"]`).click();return;}
 if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();$(e.key==='ArrowUp'?'octaveUp':'octaveDown').click();return;}
 if(e.key==='.'){e.preventDefault();$('quickDot').click();return;}
 if(e.key==='Home'||e.key==='End'){e.preventDefault();selected=anchor=null;range=[];insertionSide=e.key==='Home'?'before':'after';setMode('insert');scrollToSelection();return;}
 if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();const notes=score.measures[active].notes,at=notes.findIndex(n=>n.id===selected),previous=at>0?notes[at-1]?.id:null;const writing=mode==='insert';$('delete').click();if(writing&&at>=0){selected=anchor=previous;insertionSide=previous?'after':'before';draw();}return;}
 if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const all=events(),i=all.findIndex(x=>x.n.id===selected),target=all[Math.max(0,Math.min(all.length-1,i+(e.key==='ArrowRight'?1:-1)))];if(target){select(target.n.id,target.mi,e.shiftKey);scrollToSelection();}return;}
 if(e.key==='Escape'){selected=anchor=null;range=[];insertionSide='after';setMode('select');}
 if(e.key===' '&&e.target.closest('[data-note]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true,shiftKey:e.shiftKey}));}

});
let restored=false;try{const saved=localStorage.getItem(draftKey);if(saved){const session=JSON.parse(saved);score=validate(session.score);fileName=session.fileName||safeName(score.title);savedSnapshot=session.savedSnapshot??null;isNew=!!session.isNew;fileState=session.fileState||'已恢复草稿';restored=true;}else{const legacy=localStorage.getItem(requested?'jianpu-v2:'+requested:'jianpu-v2');if(legacy){score=parse(legacy);fileName=safeName(score.title);savedSnapshot=null;isNew=false;fileState='已恢复旧草稿';restored=true;}}}catch{message('旧草稿无法读取，可以从文件重新打开。',true);}
drawRecents();setMode('insert');syncFields();draw();requestAnimationFrame(()=>{if(innerWidth<620){zoom=75;$('zoom').value='75';draw();}else fit();});if(requested&&!restored)loadPath(requested);else if(restored)message('已恢复本地草稿');

// The workspace opens generated scores through the existing unsaved-document guard.
window.addEventListener('message',event=>{if(parent===window||event.source!==parent||event.origin!==location.origin)return;if(event.data?.type==='workspace:open-score'&&typeof event.data.path==='string')guard(()=>loadPath(event.data.path));});
