import {encodeWave,capturePermissionDenied,captureErrorMessage} from './capture-audio.js';
export function createAudioCapture({host,getBusy,acceptFile,beforeCapture,onState=()=>{}}){
 const pane=document.createElement('section');pane.className='audio-capture-panel';pane.innerHTML=`<h3>录入正在播放的音乐</h3><div class="capture-actions"><button type="button" data-capture="tab">录制浏览器标签页</button><button type="button" data-capture="apps">选择本机 App</button></div><div data-capture="appFields" hidden><label>正在播放的 App<select data-capture="app"></select></label><button type="button" data-capture="appStart">开始录制这个 App</button></div><p class="hint">浏览器：选择播放音乐的标签页，并勾选共享音频。本机 App：先运行 npm run audio:capture-setup，首次使用需允许 macOS 屏幕与系统音频录制。</p><progress data-capture="level" value="0" max="1" aria-label="采集音量"></progress><div data-capture="permissions" hidden><strong>需要 macOS 录制权限</strong><p>系统设置 → 隐私与安全性 → 屏幕与系统音频录制。允许启动开发服务的应用（如 Terminal、iTerm 或实际列出的采集程序），不是选择网易音乐。若系统要求重开应用，请先保存工程，再按提示重开。</p><a href="x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture">打开 macOS 录制权限设置</a></div><p data-capture="status" role="status">录完先试听，再导入识别。最长10分钟。</p><div class="capture-actions"><button type="button" data-capture="stop" disabled>停止录制</button><button type="button" data-capture="cancel" disabled>取消</button></div><audio data-capture="preview" controls hidden></audio><button type="button" data-capture="import" disabled>使用录音进行识别</button>`;host.append(pane);
 const $=n=>pane.querySelector(`[data-capture="${n}"]`);let state='idle',stream=null,context=null,node=null,source=null,chunks=[],frames=0,recorded=null,url=null,timer=null,jobId=null,generation=0,peak=0;
 const active=()=>['requesting','recording','stopping'].includes(state),say=t=>{$('status').textContent=captureErrorMessage(t);$('permissions').hidden=!capturePermissionDenied(t);};
 function refresh(notify=true){for(const n of ['tab','apps','appStart'])$(n).disabled=active()||getBusy();$('stop').disabled=state!=='recording';$('cancel').disabled=!active();$('import').disabled=!recorded||active()||getBusy();if(notify)onState();}
 async function json(r){let v;try{v=await r.json();}catch{throw Error('采集接口尚未加载，请在你自己的终端重启 npm run dev');}if(!r.ok)throw Error(v.error||'采集失败');return v;}
 function clearPreview(){recorded=null;if(url)URL.revokeObjectURL(url);url=null;$('preview').removeAttribute('src');$('preview').hidden=true;}
 function cleanup(){clearInterval(timer);timer=null;if(node){node.port.onmessage=null;node.disconnect();node=null;}source?.disconnect();source=null;stream?.getTracks().forEach(t=>t.stop());stream=null;context?.close().catch(()=>{});context=null;$('level').value=0;}
 function ready(blob,name){clearPreview();recorded=new File([blob],name,{type:blob.type});url=URL.createObjectURL(recorded);$('preview').src=url;$('preview').hidden=false;state='ready';say('录制完成。先播放这段录音，确认有音乐，再点“使用录音进行识别”。');refresh();}
 async function beginTab(){if(active()||getBusy())return;clearPreview();const token=++generation;state='requesting';refresh();beforeCapture();say('请选择正在播放音乐的标签页，并勾选共享标签页音频。');
 try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error('当前浏览器不支持标签页音频采集，请在 Chrome 打开本机主页。');const incoming=await navigator.mediaDevices.getDisplayMedia({video:true,audio:{suppressLocalAudioPlayback:false},systemAudio:'include',selfBrowserSurface:'exclude'});if(token!==generation){incoming.getTracks().forEach(t=>t.stop());return;}stream=incoming;if(!stream.getAudioTracks().length)throw Error('没有取得音频轨。请重新选择“浏览器标签页”并勾选“共享音频”；本机App请用另一个入口。');context=new AudioContext({sampleRate:22050});await context.resume();await context.audioWorklet.addModule('/src/capture-worklet.js');if(token!==generation)return;source=context.createMediaStreamSource(new MediaStream(stream.getAudioTracks()));node=new AudioWorkletNode(context,'jianpu-audio-recorder');chunks=[];frames=0;peak=0;const rate=context.sampleRate;node.port.onmessage=e=>{if(state!=='recording')return;const c=e.data;chunks.push(c);frames+=c.length;let maximum=0;for(const x of c)maximum=Math.max(maximum,Math.abs(x));peak=Math.max(peak,maximum);$('level').value=Math.min(1,maximum*3);say(`正在录制 ${Math.floor(frames/rate)}秒${peak<.0001?' · 尚未检测到声音，请播放音乐':''}`);if(frames>=rate*600)finishTab();};source.connect(node).connect(context.destination);state='recording';for(const t of stream.getTracks())t.addEventListener('ended',()=>{if(state==='recording')finishTab();},{once:true});refresh();}catch(e){if(token!==generation)return;cleanup();state='idle';say(e.name==='NotAllowedError'?'没有授予采集权限或已取消选择。':e.message);refresh();}}
 function finishTab(){if(state!=='recording')return;state='stopping';const rate=context.sampleRate;cleanup();try{if(peak<.0001)throw Error('录音没有检测到声音，未导入。请确认目标正在播放并已共享音频。');ready(new Blob([encodeWave(chunks,rate)],{type:'audio/wav'}),'标签页录音-'+new Date().toISOString().replaceAll(':','-')+'.wav');}catch(e){state='idle';say(e.message);refresh();}finally{chunks=[];}}
 $('tab').onclick=beginTab;
 $('apps').onclick=async()=>{if(active()||getBusy())return;state='requesting';refresh();say('读取正在运行的App；请在macOS权限提示中允许录制。');const token=++generation;try{const data=await json(await fetch('/api/capture/apps',{method:'POST'}));if(token!==generation)return;$('app').replaceChildren();for(const a of data.apps)$('app').append(new Option(a.name+' · '+a.bundleId,a.bundleId));$('appFields').hidden=false;say('选择音乐所在的App。采集只针对所选App，不使用麦克风。');}catch(e){if(token===generation)say(e.message);}finally{if(token===generation){state='idle';refresh();}}};
 $('appStart').onclick=async()=>{if(active()||getBusy())return;const bundleId=$('app').value;if(!bundleId){say('先选择一个App');return;}beforeCapture();clearPreview();state='requesting';refresh();const token=++generation;try{const j=await json(await fetch('/api/capture/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bundleId})}));if(token!==generation){fetch('/api/capture/jobs/'+j.id,{method:'DELETE',keepalive:true}).catch(()=>{});return;}jobId=j.id;timer=setInterval(async()=>{try{const value=await json(await fetch('/api/capture/jobs/'+j.id));if(token!==generation)return;if(value.status==='recording'){state='recording';say(`正在录制所选App ${value.seconds}秒`);refresh();}else if(value.status==='done'){clearInterval(timer);timer=null;state='stopping';const r=await fetch('/api/capture/jobs/'+j.id+'/audio');if(!r.ok)throw Error('读取录音失败');const blob=await r.blob();if(token!==generation)return;jobId=null;ready(blob,'App录音-'+new Date().toISOString().replaceAll(':','-')+'.m4a');}else if(['error','cancelled'].includes(value.status)){throw Error(value.message);}else say(value.message);}catch(e){if(token!==generation)return;clearInterval(timer);timer=null;state='idle';say(e.message);refresh();}},1000);}catch(e){if(token===generation){state='idle';say(e.message);refresh();}}};
 $('stop').onclick=async()=>{if(jobId){state='stopping';refresh();try{await json(await fetch('/api/capture/jobs/'+jobId+'/stop',{method:'POST'}));say('正在保存录音…');}catch(e){say(e.message);state='recording';refresh();}}else finishTab();};
 function cancel(){generation++;if(jobId)fetch('/api/capture/jobs/'+jobId,{method:'DELETE',keepalive:true}).catch(()=>{});jobId=null;state='idle';cleanup();chunks=[];say('已取消录制');refresh();}
 $('cancel').onclick=cancel;$('import').onclick=async()=>{if(!recorded||getBusy())return;$('preview').pause();await acceptFile(recorded);};
 window.addEventListener('pagehide',cancel);window.addEventListener('workspace-hidden',()=>{if(active())cancel();});window.addEventListener('project-restore',()=>{if(active())cancel();});refresh();return {active,refresh};
}
