import {render} from './render.js';
import {layout} from './layout.js';
import {prepareModelScore} from './model-score-import.js';
import {compareScores,comparisonTimelines,applyComparisonSuggestion} from './score-compare.js';
const $=id=>document.getElementById(id);let project,left,right,comparison,times,timedLyrics=null,history=[],sources=[],scrollFrame=0;
const chosen={left:null,right:null},localScores={left:null,right:null},loadGeneration={left:0,right:0},loadedSignature={left:null,right:null};
const scrollRestore={left:null,right:null};let scrollRestoreFrame=0;
const message=(text,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error);};
const asset=path=>`/api/projects/${project.id}/asset?path=${encodeURIComponent(path)}`;
function draw(){const source=right?.importSource||{},warnings=[];for(const n of source.pendingNotes||[])warnings.push(`待核对音符：第 ${n.measure} 小节 ${n.noteId}（${(n.fields||[]).join('、')}）；显示内容为占位修复。`);for(const l of source.pendingLyrics||[])warnings.push(`待定位歌词：第 ${l.measure||'?'} 小节“${l.text||''}”（原引用 ${l.noteId||'无'}）；文字保留，未自动移位。`);for(const c of source.pendingChords||[])warnings.push(`待核对和弦：${c?.label||'名称或小节位置不明'}。`);for(const m of source.pendingMetadata||[])warnings.push(`待核对附加信息：${JSON.stringify(m).slice(0,140)}。`);const auto=(right?.visionReview?.issues||[]).filter(i=>typeof i==='object'&&i.kind).map(i=>`${i.measure?`第 ${i.measure} 小节：`:''}${i.description||i.kind}`);$('reviewWarnings').textContent=[...warnings,...auto].join('；');for(const [id,s] of [['left',left],['right',right]]){const sheet=$(id);scrollRestore[id]??=sheet.scrollTop;sheet.innerHTML=s?render(s):'<p>尚无此类乐谱。请先识别或加载 JPU。</p>';}if(!scrollRestoreFrame)scrollRestoreFrame=requestAnimationFrame(()=>{for(const id of ['left','right']){$(id).scrollTop=scrollRestore[id]??0;scrollRestore[id]=null;}scrollRestoreFrame=0;});$('adopt').disabled=!right;$('undo').disabled=!history.length;if($('audio').paused)paint();}
function mark(){for(const id of ['left','right'])for(const g of $(id).querySelectorAll('.flag'))g.classList.remove('flag');if(!comparison||!$('showMarks').checked)return;for(const issue of comparison.issues)for(const [id,index,entries] of [['left',issue.audio,comparison.a],['right',issue.visual,comparison.b]]){const n=entries[index]?.n;if(n)$(id).querySelector(`[data-note="${CSS.escape(n.id)}"]`)?.classList.add('flag');}}
const label=n=>n?`${n.accidental===1?'♯':n.accidental===-1?'♭':''}${n.degree}（八度 ${n.octave}，${n.base}分${n.dots?'附点':''}）`:'未匹配';
function analyze(){if(!left||!right){message('需要音频谱和视觉谱各一份',true);$('alignmentInfo').textContent='请先选择左右两份乐谱。';return;}try{
 comparison=compareScores(left,right);times=comparisonTimelines(left,right,comparison,{timedLyrics});
 $('alignmentInfo').textContent=times.alignment.description;
 $('alignmentInfo').classList.toggle('alignment-fallback',times.alignment.method!=='lyrics');
 mark();$('issues').replaceChildren();for(const issue of comparison.issues){const row=document.createElement('div');row.className='issue';const a=comparison.a[issue.audio],b=comparison.b[issue.visual],text=document.createElement('span');text.textContent=`${b?`视觉第 ${b.mi+1} 小节`:''} ${a?`音频第 ${a.mi+1} 小节`:''}：${label(b?.n)} → 候选 ${label(a?.n)}。${issue.description}`;row.append(text);const listen=document.createElement('button');listen.textContent='听此处';listen.onclick=()=>seek(issue.audio,issue.visual);row.append(listen);if(issue.type==='difference'){for(const [caption,fields] of [['确认音高',['pitch']],['确认时值',['duration']]]){const button=document.createElement('button');button.textContent=caption;button.onclick=()=>{try{const next=applyComparisonSuggestion(right,left,issue,fields);history.push(structuredClone(right));right=next;draw();analyze();save();message('已确认并修改右侧比较稿；工程谱尚未替换。');}catch(e){message(e.message,true);}};row.append(button);}}const reject=document.createElement('button');reject.textContent='保留视觉原值';reject.onclick=()=>{row.remove();message('已保留视觉原值；谱面没有修改。');};row.append(reject);$('issues').append(row);}if(!comparison.issues.length)$('issues').textContent='音高与时值序列一致（未比较歌词、和弦及反复展开）。';message(`${left.key!==right.key?'注意：两谱实际 Do 不同（'+left.key+' / '+right.key+'），先核对调性；':''}已发现 ${comparison.issues.length} 处差异；匹配 ${comparison.pairs.length} 对音符。${times.alignment.method==='lyrics'?'指针已按共同歌词对齐。':'共同歌词不足，指针仍按音符估算。'}建议仅供人工确认。`);
 }catch(e){$('alignmentInfo').textContent='歌词时间线对齐失败：'+e.message;message(e.message,true);}}
function seek(a,b){const segment=a!==undefined?times?.audio[a]:times?.visual.find(x=>x.id===comparison.b[b]?.n.id);if(segment){$('audio').currentTime=Math.max(0,segment.start+Number($('offset').value||0));$('audio').play().catch(e=>message(e.message,true));}}
function save(){if(!project||!right)return;chosen.right='comparison';loadedSignature.right=JSON.stringify(right);project.workspace.comparison={score:right};updateSources();parent.postMessage({type:'compare:save',score:right,projectId:project.id},location.origin);}
async function loadTimedLyrics(source){const path=`runs/${source.id}/lyrics-alignment.json`;if(!project?.assets?.some(x=>x.path===path))return null;try{const response=await fetch(asset(path));if(!response.ok)return null;const value=await response.json();return Array.isArray(value.characters)?value:null;}catch{return null;}}
function updateSources(){if(!project)return;const p=project;sources=[{id:'current',name:'当前工程谱（随编辑更新）',score:p.score},...(p.history||[]).map(h=>({id:h.id,name:'修订：'+new Date(h.savedAt).toLocaleString(),score:h.score})),...(p.runs||[]).filter(r=>r.status==='done').map(r=>({id:r.id,name:'MP3 原始识别：'+new Date(r.createdAt).toLocaleString(),path:`runs/${r.id}/recognized.jpu`}))];if(p.workspace?.modelImage?.score)sources.unshift({id:'visual',name:'最新大模型视觉谱',score:p.workspace.modelImage.score});if(p.workspace?.comparison?.score)sources.unshift({id:'comparison',name:'双谱比较稿（保留已确认修改）',score:p.workspace.comparison.score});for(const side of ['left','right'])if(localScores[side])sources.push({id:`local-${side}`,name:`${side==='left'?'左':'右'}侧加载的 JPU`,score:localScores[side]});for(const side of ['left','right']){const picker=$(side+'Source');picker.replaceChildren();for(const s of sources)picker.append(new Option(s.name,s.id));if(chosen[side])picker.value=chosen[side];}}
async function select(side,value,{keepHistory=false}={}){const g=++loadGeneration[side],source=sources.find(x=>x.id===value);if(!source)return;try{const s=source.score||await fetch(asset(source.path)).then(r=>{if(!r.ok)throw Error('该识别版本没有保存谱面，请先在听歌页生成乐谱');return r.json();});if(g!==loadGeneration[side])return;const signature=JSON.stringify(s);if(chosen[side]===value&&loadedSignature[side]===signature)return;const prepared=prepareModelScore(signature).score;if(side==='left'){left=prepared;timedLyrics=await loadTimedLyrics(source.id==='current'?{id:project.scoreBasedOn}:source);}else right=prepared;if(g!==loadGeneration[side])return;chosen[side]=value;loadedSignature[side]=signature;$(side+'Source').value=value;if(!keepHistory)history=[];draw();if(left&&right)analyze();}catch(e){message(e.message,true);}}
async function restore(p){const changed=project?.id!==p.id;if(changed){left=right=null;timedLyrics=null;history=[];comparison=times=null;chosen.left=chosen.right=null;localScores.left=localScores.right=null;loadedSignature.left=loadedSignature.right=null;}project=p;updateSources();const run=sources.find(s=>s.id===p.scoreBasedOn)||sources.filter(s=>s.path).at(-1);const currentAudio=!!(p.scoreBasedOn||p.score?.transcription);const defaults={left:currentAudio?'current':run?.id||'current',right:!currentAudio&&run?'current':p.workspace?.comparison?.score?'comparison':p.workspace?.modelImage?.score?'visual':currentAudio?null:'current'};if(p.source){const url=asset(p.source.path);if($('audio').getAttribute('src')!==url)$('audio').src=url;}else{$('audio').removeAttribute('src');message('工程没有原歌，请先导入 MP3',true);}for(const side of ['left','right']){const value=chosen[side]&&sources.some(s=>s.id===chosen[side])?chosen[side]:defaults[side];if(value)await select(side,value,{keepHistory:!changed});else{chosen[side]=null;loadedSignature[side]=null;if(side==='left'){left=null;timedLyrics=null;}else right=null;draw();}}if(!right)message('请先在大模型页生成视觉谱，或右侧加载 JPU');}
for(const side of ['left','right']){$(side+'Source').onchange=()=>select(side,$(side+'Source').value);$(side+'File').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const s=prepareModelScore(await file.text()).score;localScores[side]=s;updateSources();await select(side,`local-${side}`);}catch(e){message(e.message,true);}};$(side).addEventListener('scroll',()=>{if(!$('sync').checked||scrollFrame||!$('audio').paused&&$('follow').checked)return;const from=$(side),to=$(side==='left'?'right':'left');const ratio=from.scrollTop/Math.max(1,from.scrollHeight-from.clientHeight);to.scrollTop=ratio*Math.max(0,to.scrollHeight-to.clientHeight);scrollFrame=requestAnimationFrame(()=>scrollFrame=0);});$(side).onclick=e=>{const group=e.target.closest('[data-note]');if(!group||!times)return;const segment=times[side==='left'?'audio':'visual'].find(x=>x.id===group.dataset.note);if(segment&&Number.isFinite(segment.start)){$('audio').currentTime=Math.max(0,segment.start+Number($('offset').value||0));}};}
function paint(){const time=$('audio').currentTime-Number($('offset').value||0);for(const [side,s] of [['left',left],['right',right]]){if(!s||!times)continue;const container=$(side),svg=container.querySelector('svg');if(!svg)continue;svg.querySelector('.playhead')?.remove();for(const n of container.querySelectorAll('.active-note'))n.classList.remove('active-note');const segment=times[side==='left'?'audio':'visual'].find(x=>time>=x.start&&time<x.end);if(!segment)continue;const plan=layout(s),p=plan.positions.get(segment.id);if(!p)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.classList.add('playhead');for(const [k,v] of Object.entries({x1:p.x,x2:p.x,y1:p.y-42,y2:p.y+52,stroke:'#c45d32','stroke-width':2,'stroke-dasharray':segment.timingSource?.startsWith('estimated')?'4 3':'none'}))line.setAttribute(k,v);svg.append(line);container.querySelector(`[data-note="${CSS.escape(segment.id)}"]`)?.classList.add('active-note');if($('follow').checked&&!$('audio').paused){const y=(p.y-60)/plan.height*svg.getBoundingClientRect().height;if(y<container.scrollTop||y>container.scrollTop+container.clientHeight-100)container.scrollTop=Math.max(0,y-40);}}if(!$('audio').paused)requestAnimationFrame(paint);}
$('audio').addEventListener('play',paint);$('audio').addEventListener('timeupdate',()=>{if($('audio').paused)paint();});$('audio').addEventListener('seeked',()=>{if($('audio').paused)paint();});$('showMarks').onchange=mark;$('compare').onclick=analyze;$('reload').onclick=()=>{if(project)fetch('/api/projects/'+project.id).then(r=>r.json()).then(restore).catch(e=>message(e.message,true));};$('undo').onclick=()=>{if(history.length){right=history.pop();draw();analyze();save();}};$('adopt').onclick=()=>{if(right){chosen.right='current';parent.postMessage({type:'workspace:import-score',score:right},location.origin);}};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='project:restore')restore(e.data.project).catch(error=>message(error.message,true));if(e.data?.type==='project:saved'&&project&&e.data.projectId===project.id&&JSON.stringify(project.score)!==JSON.stringify(e.data.score))restore({...project,score:e.data.score,revision:e.data.revision}).catch(error=>message(error.message,true));if(e.data?.type==='compare:error')message(e.data.message,true);});parent.postMessage({type:'workspace:ready'},location.origin);
