import {setGuitarNotation,displayChordLabel,concertChordLabel,recommendedCapo,guitarCaption} from './guitar-notation.js';
import {tidyDetectedRests} from './rest-cleanup.js';
import {moveAlignedCharacter,applyAcousticLyrics} from './lyric-alignment.js';
import {downloadFile,safeName} from './files.js';
import {render} from './render.js';
import {layout} from './layout.js';
import {note,change,remove,validate,used,connect,detachInterruptedTies} from './model.js';
import {emptyMeasure,insertMeasureAfter,copySelection,pasteSelection} from './commands.js';
import {setLyric,relocateLyricTail} from './lyrics.js';
import {insertBarline,deleteBarline,moveBarline} from './barline-editing.js';

export function createScoreEditor({container,toolbar,getScore,onChange,onAnalyzeChords=()=>{},onRender=()=>{},onSeek=()=>{},onModeChange=()=>{},getAuxiliaryState=()=>null,intercept=()=>false,message=()=>{}}){
 let selected=null,selectedCharacter=null,active=0,boundary=null,mode='select',base=4,octave=0,dots=0,side='after',undo=[],redo=[],range=[],anchor=null,clipboard=null,drag=null,suppress=false,inline=null,composing=false;
 toolbar.innerHTML=`<div class="score-tools" role="toolbar" aria-label="谱面编辑工具">
 <button data-edit-action="undo" aria-label="撤销谱面编辑">↶</button><button data-edit-action="redo" aria-label="重做谱面编辑">↷</button><span class="tool-divider"></span>
 <button data-edit-mode="select" aria-pressed="true">选择 / 改音</button><button data-edit-mode="write" aria-pressed="false">写谱</button><button data-edit-mode="lyrics" aria-pressed="false">歌词</button><button data-edit-mode="bars" aria-pressed="false">小节线</button><span class="tool-divider"></span>
 <label>时值 <select data-edit-field="base" aria-label="输入音符时值"><option value="1">全音符</option><option value="2">二分</option><option value="4" selected>四分</option><option value="8">八分</option><option value="16">十六分</option></select></label>
 <label>八度 <select data-edit-field="octave" aria-label="音符八度"><option value="-2">低两组</option><option value="-1">低音</option><option value="0" selected>中音</option><option value="1">高音</option><option value="2">高两组</option></select></label><button data-edit-action="dot" aria-pressed="false">附点</button>
 <button data-edit-action="insert-line">＋ 小节线</button><button data-edit-action="delete-line">删除小节线</button><button data-edit-action="chords">识别和弦</button><button data-edit-action="edit-chord">改和弦</button><button data-edit-action="tidy-rests">整理短休止</button><button data-edit-action="insert-lyric">补字 / 编辑歌词</button><button data-edit-action="empty-bar">＋ 空小节</button><button data-edit-action="delete">删除音符</button>
 <button data-edit-action="tie">延音线</button><button data-edit-action="slur">圆滑线</button><details class="score-more"><summary>更多</summary><div><button data-edit-action="copy">复制 ⌘C</button><button data-edit-action="cut">剪切 ⌘X</button><button data-edit-action="paste">粘贴 ⌘V</button><button data-edit-action="select-all">全选 ⌘A</button><button data-edit-action="svg">导出 SVG</button><button data-edit-action="print">打印 / PDF</button></div></details>
 </div><div class="score-tools score-tools-secondary"><span>输入音符</span><span data-edit-notes></span><label>升降 <select data-edit-field="accidental"><option value="0">还原</option><option value="1">升 ♯</option><option value="-1">降 ♭</option></select></label><label>插入位置 <select data-edit-field="side"><option value="after">所选音后</option><option value="before">所选音前</option></select></label><label>歌词段落 <select data-edit-field="verse"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>拖歌词 <select data-edit-field="lyric-scope"><option value="single">只拖这个字</option><option value="tail">本行后续跟随</option></select></label><label>吉他和弦 <select data-edit-field="guitar-mode"><option value="concert">实际和弦</option><option value="C">C 指型</option><option value="G">G 指型</option></select></label><label>Capo <input data-edit-field="guitar-capo" aria-label="吉他 Capo 品数" type="number" min="0" max="12" value="0" style="width:54px"></label><button data-edit-action="guitar-apply">确认并更新和弦</button><span data-edit-status role="status"></span></div>`;
 toolbar.insertAdjacentHTML('beforeend', `<div class="score-edit-dock" role="toolbar" aria-label="常驻编辑模式"><strong>编辑乐谱</strong><button data-edit-mode="select">改音符</button><button data-edit-mode="write">插入音符</button><button data-edit-mode="lyrics">编辑歌词</button><button data-edit-mode="bars">编辑小节线</button></div>`);
 const field=name=>toolbar.querySelector(`[data-edit-field="${name}"]`),find=id=>getScore()?.measures.flatMap((m,mi)=>m.notes.map(n=>({n,mi}))).find(e=>e.n.id===id);
 const focus=()=>container.focus({preventScroll:true});container.tabIndex=0;
 function state(){return {score:structuredClone(getScore()),selected,active,boundary,range:[...range],anchor,auxiliary:getAuxiliaryState()};}
 function restore(s){({selected,active,boundary,range,anchor}=s);onChange(s.score,{restoredAuxiliary:s.auxiliary});draw();}
 function commit(fn,text){if(!getScore())return false;const prior=state(),next=structuredClone(prior.score);try{fn(next);validate(next);undo.push(prior);if(undo.length>100)undo.shift();redo=[];onChange(next,{action:text});draw();message(text);return true;}catch(e){({selected,active,boundary,range,anchor}=prior);message(e.message,true);draw();return false;}}
 function sync(){const e=find(selected);if(e){active=e.mi;base=e.n.base;octave=e.n.octave;dots=e.n.dots;field('accidental').value=e.n.accidental||0;}field('base').value=base;field('octave').value=octave;toolbar.querySelector('[data-edit-action=dot]').setAttribute('aria-pressed',String(!!dots));}
 function draw(){
  let score=getScore();if(!score)return;if(score.lyricAlignment?.characters?.length&&score.lyricAlignment.displayMode!=='characters'){score=applyAcousticLyrics(score,score.lyricAlignment,{verse:score.lyricAlignment.verse||1}).score;onChange(score,{action:'恢复逐字歌词编辑'});}toolbar.querySelectorAll('[data-edit-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.editMode===mode)));active=Math.min(active,score.measures.length-1);if(selected&&!find(selected))selected=null;
  container.innerHTML=render(score,selected,active,false,range,mode==='write'?{mi:active,index:insertionIndex()}:null,mode==='lyrics'?+field('verse').value:0);
  field('guitar-mode').value=score.guitarNotation?.mode==='fingering'?score.guitarNotation.shapeKey:'concert';field('guitar-capo').value=score.guitarNotation?.capo||0;
  const svg=container.querySelector('svg');if(selectedCharacter){const g=svg.querySelector(`[data-timed-lyric="${CSS.escape(selectedCharacter)}"]`);g?.classList.add('selected-lyric');}const plan=layout(score,mode==='lyrics'?+field('verse').value:0),ns='http://www.w3.org/2000/svg';
  plan.measures.slice(0,-1).forEach(p=>{const group=document.createElementNS(ns,'g');group.dataset.barline=p.mi;group.setAttribute('role','button');group.setAttribute('tabindex','0');group.setAttribute('aria-label',`第 ${p.mi+1} 小节后的线，拖动移动，Delete 删除`);group.classList.add('editable-barline');if(boundary===p.mi)group.classList.add('selected-barline');const x=p.x+p.width-5;group.innerHTML=`<rect x="${x-9}" y="${p.y-31}" width="18" height="63" fill="transparent"/><line x1="${x}" x2="${x}" y1="${p.y-27}" y2="${p.y+23}"/><circle cx="${x}" cy="${p.y+30}" r="3"/>`;svg.append(group);});
  for(const m of plan.measures){const ticks=used(m.m),capacity=score.meter[0]*16;if(ticks!==capacity){const label=document.createElementNS(ns,'text');label.classList.add('bar-capacity');label.setAttribute('x',m.x+40);label.setAttribute('y',m.y-37);label.textContent=`${ticks/16}/${score.meter[0]} 拍`;svg.append(label);}}
  toolbar.querySelector('[data-edit-action=undo]').disabled=!undo.length;toolbar.querySelector('[data-edit-action=redo]').disabled=!redo.length;
  toolbar.querySelector('[data-edit-status]').textContent=boundary!==null?`已选小节线 ${boundary+1} · 拖动移动 / Delete 删除`:`第 ${active+1} 小节 · ${mode==='write'?'0–7 连续输入；[ ] 改时值；↑ ↓ 八度':mode==='lyrics'?'点字 / 空格直接输入；一音可填多个字':mode==='bars'?'点音符插入线；拖线移动；选线后删除':'点音符选中，0–7 改音；双击试听'}`;
  onRender();
 }
 function insertionIndex(){const m=getScore()?.measures[active];if(!m)return 0;const at=m.notes.findIndex(n=>n.id===selected);return at<0?m.notes.length:at+(side==='after'?1:0);}
 function setMode(value){if(!flush())return;mode=value;onModeChange(value);toolbar.querySelectorAll('[data-edit-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.editMode===mode)));draw();focus();}
 function input(degree,half=false){if(mode==='select'&&selected){commit(s=>{const e=find(selected);s.spans=s.spans.filter(p=>p.type!=='tie'||p.from!==selected&&p.to!==selected);change(s,e.mi,selected,{degree,...(degree?{}:{octave:0})});detachInvalidTies(s);},'已修改音高');return;}
  if(mode!=='write')setMode('write');if(half&&base===16){message('最短支持十六分音符',true);return;}
  commit(s=>{let at=insertionIndex(),m=s.measures[active];if(used(m)>=s.meter[0]*16&&at===m.notes.length){active++;if(active===s.measures.length)s.measures.push(emptyMeasure());m=s.measures[active];at=0;}
   const n=note(degree,half?base*2:base,degree?octave:0,dots);if(degree&&+field('accidental').value)n.accidental=+field('accidental').value;m.notes.splice(at,0,n);s.manualBarlines=true;detachInterruptedTies(s);selected=n.id;range=[];anchor=selected;boundary=null;side='after';},'已输入音符');focus();
 }
 function detachInvalidTies(s){const all=s.measures.flatMap(m=>m.notes),byId=new Map(all.map(n=>[n.id,n]));s.spans=s.spans.filter(p=>p.type!=='tie'||(byId.get(p.from)?.degree===byId.get(p.to)?.degree&&byId.get(p.from)?.octave===byId.get(p.to)?.octave&&(byId.get(p.from)?.accidental||0)===(byId.get(p.to)?.accidental||0)&&byId.get(p.from)?.degree));}
 function editProperty(patch){if(selected&&mode==='select')commit(s=>{const e=find(selected);if(patch.octave!==undefined||patch.accidental!==undefined)s.spans=s.spans.filter(p=>p.type!=='tie'||p.from!==selected&&p.to!==selected);change(s,e.mi,selected,patch);detachInvalidTies(s);},'已修改音符');else draw();focus();}
 const actions={
  undo(){if(!flush()||!undo.length)return;redo.push(state());restore(undo.pop());message('已撤销');},redo(){if(!flush()||!redo.length)return;undo.push(state());restore(redo.pop());message('已重做');},
  'insert-line'(){if(!flush())return;commit(s=>{boundary=insertBarline(s,selected);},'已插入小节线，音符和歌词保留');},
  'delete-line'(){if(!flush())return;if(boundary===null){message('先点击要删除的小节线',true);return;}commit(s=>{active=deleteBarline(s,boundary);boundary=null;},'已删除小节线，合并两侧音符');},
  'guitar-apply'(){const shapeKey=field('guitar-mode').value,capo=+field('guitar-capo').value;if(field('guitar-capo').value.trim()===''){message('请填写 Capo 品数',true);return;}if(!flush())return;commit(s=>Object.assign(s,setGuitarNotation(s,{shapeKey:shapeKey==='concert'?'C':shapeKey,capo,enabled:shapeKey!=='concert'})),'已更新吉他指型和弦；旋律数字与MIDI保持不变');const caption=guitarCaption(getScore());if(caption)message(caption);},
  chords(){if(flush())onAnalyzeChords();},
  'insert-lyric'(){if(!selected){message('先点要补字的音符，再点「补字 / 编辑歌词」',true);return;}openLyric(selected,+field('verse').value);},
  'edit-chord'(){if(!flush())return;const m=getScore().measures[active],old=(getScore().chords||[]).find(c=>c.measureId===m.id),label=prompt('本小节和弦（如 C、Am、G7；留空删除）',old?displayChordLabel(getScore(),old.label):'');if(label===null)return;if(label&&!/^[A-G](?:#|b)?(?:m|maj|dim|aug|sus|add)?[0-9]*(?:\/[A-G](?:#|b)?)?$/.test(label.trim())){message('请输入和弦字母，如 Am 或 G7',true);return;}commit(s=>{s.chords=(s.chords||[]).filter(c=>c.measureId!==m.id);if(label.trim())s.chords.push({measureId:m.id,label:concertChordLabel(s,label.trim()),source:'manual'});},'已更新本小节和弦');},
  'tidy-rests'(){if(!flush())return;let count=0;commit(s=>{const result=tidyDetectedRests(s);Object.assign(s,result.score);count=result.count;},'已整理短休止（可撤销）');message(`已将 ${count} 个短休止并入前音；保留长停顿和小节时长`);},
  'empty-bar'(){if(!flush())return;commit(s=>{active=insertMeasureAfter(s,active);selected=null;range=[];anchor=null;boundary=null;},'已在所选小节后插入空小节');setMode('write');},
  copy(){try{clipboard=copySelection(getScore(),range.length?range:[selected]);message('已复制音符和歌词');}catch(e){message(e.message,true);}},cut(){actions.copy();if(clipboard)actions.delete();},paste(){commit(s=>{s.manualBarlines=true;const added=pasteSelection(s,active,selected,clipboard);selected=added.at(-1);range=added;boundary=null;},'已粘贴音符和歌词');},'select-all'(){range=getScore()?.measures.flatMap(m=>m.notes.map(n=>n.id))||[];selected=range.at(-1);draw();},svg(){downloadFile(render(getScore(),null,-1,true),safeName(getScore().title).replace(/\.jpu$/,'.svg'),'image/svg+xml');},print(){const tab=window.open('','_blank');if(!tab){message('请允许打开打印窗口',true);return;}tab.document.write('<html><head><title>简谱</title><style>body{margin:12mm}svg{width:100%}@page{margin:10mm}</style></head><body>'+render(getScore(),null,-1,true)+'</body></html>');tab.document.close();tab.focus();tab.print();},
  delete(){if(boundary!==null){actions['delete-line']();return;}if(!selected)return;commit(s=>{remove(s,range.length?range:[selected]);selected=null;range=[];},'已删除音符');},
  dot(){dots=dots?0:1;editProperty({dots});},
  tie(){link('tie');},slur(){link('slur');}
 };
 function link(type){const all=getScore()?.measures.flatMap(m=>m.notes)||[],i=all.findIndex(n=>n.id===selected);if(i<0||i===all.length-1){message('先选择连线的起音（连接下一音）',true);return;}commit(s=>connect(s,type,selected,all[i+1].id),'已添加连线');}
 toolbar.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.editMode)setMode(button.dataset.editMode);else if(button.dataset.editAction){actions[button.dataset.editAction]?.();if(button.dataset.editAction!=='insert-lyric')focus();}else if(button.dataset.editDegree!==undefined)input(+button.dataset.editDegree);});
 for(let d=0;d<=7;d++){const b=document.createElement('button');b.textContent=d;b.dataset.editDegree=d;b.setAttribute('aria-label',`输入音符 ${d}`);toolbar.querySelector('[data-edit-notes]').append(b);}
 field('guitar-mode').onchange=()=>{const shapeKey=field('guitar-mode').value;if(shapeKey!=='concert')field('guitar-capo').value=recommendedCapo(getScore(),shapeKey);message('设置尚未应用：请点「确认并更新和弦」');};
 field('guitar-capo').oninput=()=>message('设置尚未应用：请点「确认并更新和弦」');
 field('accidental').onchange=()=>editProperty({accidental:+field('accidental').value});field('base').onchange=()=>{base=+field('base').value;editProperty({base});};field('octave').onchange=()=>{octave=+field('octave').value;editProperty({octave});};field('side').onchange=()=>{side=field('side').value;setMode('write');};field('verse').onchange=()=>{flush();draw();};
 container.addEventListener('click',e=>{if(suppress){suppress=false;return;}const n=e.target.closest('[data-note]'),bar=e.target.closest('[data-barline]'),lyric=e.target.closest('[data-lyric],[data-lyric-slot]');const timed=e.target.closest('[data-timed-lyric]');if(timed){openTimedLyric(timed.dataset.timedLyric);return;}if(lyric){const id=lyric.dataset.lyric||lyric.dataset.lyricSlot;openLyric(id,+lyric.dataset.verse);return;}if(intercept(e))return;if(bar){flush();boundary=+bar.dataset.barline;selected=null;active=boundary;draw();focus();return;}
  if(lyric){const id=lyric.dataset.lyric||lyric.dataset.lyricSlot;if(id)onSeek(id);openLyric(id,+lyric.dataset.verse);return;}
  if(n){onSeek(n.dataset.note);if(e.detail>=2&&mode!=='lyrics'&&mode!=='bars')return;if(!flush())return;if(e.shiftKey&&anchor){const ids=getScore().measures.flatMap(m=>m.notes.map(n=>n.id)),a=ids.indexOf(anchor),b=ids.indexOf(n.dataset.note);range=ids.slice(Math.min(a,b),Math.max(a,b)+1);}else{range=[];anchor=n.dataset.note;}selected=n.dataset.note;active=+n.dataset.mi;boundary=null;sync();if(mode==='bars'){actions['insert-line']();return;}if(mode==='lyrics'){openLyric(selected,+field('verse').value);return;}draw();focus();return;}
  const m=e.target.closest('[data-measure]');if(m){const first=getScore()?.measures[+m.dataset.measure]?.notes[0];if(first)onSeek(first.id);if(!flush())return;active=+m.dataset.measure;selected=null;boundary=null;draw();focus();}
 });
 container.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||e.isComposing)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?actions.redo():actions.undo();return;}if(e.metaKey||e.ctrlKey){const action={c:'copy',x:'cut',v:'paste',a:'select-all'}[e.key.toLowerCase()];if(action){e.preventDefault();actions[action]();}return;}if(e.altKey)return;
  const digit=e.code.match(/^(?:Digit|Numpad)([0-7])$/);if(digit){e.preventDefault();input(+digit[1],e.shiftKey);return;}
  if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const all=getScore().measures.flatMap((m,mi)=>m.notes.map(n=>({n,mi}))),i=all.findIndex(e=>e.n.id===selected),next=all[Math.max(0,Math.min(all.length-1,i+(e.key==='ArrowLeft'?-1:1)))];if(next){selected=next.n.id;active=next.mi;range=[];boundary=null;sync();draw();container.querySelector(`[data-note="${CSS.escape(selected)}"]`)?.scrollIntoView({block:'nearest'});}return;}
  if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();actions.delete();return;}if(e.key==='Enter'){e.preventDefault();if(mode==='lyrics')actions['insert-lyric']();else actions['empty-bar']();return;}
  if(['[',']'].includes(e.key)){e.preventDefault();const bases=[1,2,4,8,16];base=bases[Math.max(0,Math.min(4,bases.indexOf(base)+(e.key==='['?1:-1)))];field('base').value=base;editProperty({base});return;}
  if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();octave=Math.max(-2,Math.min(2,octave+(e.key==='ArrowUp'?1:-1)));field('octave').value=octave;editProperty({octave});return;}if(e.key==='.'){e.preventDefault();actions.dot();}
 });
 function openLyric(id,verse){if(!flush())return;const e=find(id);if(!e?.n.degree)return;mode='lyrics';onModeChange(mode);selected=id;active=e.mi;field('verse').value=verse;draw();const input=document.createElement('input');input.className='score-inline-lyric';input.setAttribute('aria-label','谱面歌词输入');input.value=(getScore().lyrics||[]).find(l=>l.noteId===id&&l.verse===verse)?.text||'';input.maxLength=80;container.append(input);const p=layout(getScore(),verse).positions.get(id),svg=container.querySelector('svg'),point=svg.createSVGPoint();point.x=p.x;point.y=p.y+62+(verse-1)*26;const xy=point.matrixTransform(svg.getScreenCTM()),box=container.getBoundingClientRect();Object.assign(input.style,{left:`${xy.x-box.left-40}px`,top:`${xy.y-box.top-22}px`,width:'80px'});inline={id,verse,input};input.oncompositionstart=()=>composing=true;input.oncompositionend=()=>composing=false;input.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();flush();focus();}else if(e.key==='Escape'){inline=null;input.remove();focus();}};input.onblur=()=>{if(!composing)flush();};input.focus({preventScroll:true});input.select();}
 function openTimedLyric(id){if(!flush())return;const c=getScore()?.lyricAlignment?.characters.find(c=>c.id===id);if(!c)return;mode='lyrics';onModeChange(mode);selectedCharacter=id;draw();const g=container.querySelector(`[data-timed-lyric="${CSS.escape(id)}"]`),box=g?.getBoundingClientRect(),parent=container.getBoundingClientRect();if(!box)return;const input=document.createElement('input');input.className='score-inline-lyric';input.setAttribute('aria-label','谱面歌词输入');input.value=c.text;Object.assign(input.style,{left:`${box.left-parent.left-12}px`,top:`${box.top-parent.top-5}px`,width:'80px'});container.append(input);inline={timedId:id,input};input.oncompositionstart=()=>composing=true;input.oncompositionend=()=>composing=false;input.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();flush();focus();}else if(e.key==='Escape'){inline=null;input.remove();focus();}};input.onblur=()=>{if(!composing)flush();};input.focus({preventScroll:true});input.select();}
 function flush(){if(!inline)return true;if(composing){message('请先完成汉字输入',true);return false;}const edit=inline;inline=null;const ok=commit(s=>{if(edit.timedId){const c=s.lyricAlignment.characters.find(c=>c.id===edit.timedId);c.text=edit.input.value;c.manual=true;}else setLyric(s,edit.id,edit.verse,edit.input.value);},'已在谱面保存歌词');if(!ok){if(edit.timedId)openTimedLyric(edit.timedId);else openLyric(edit.id,edit.verse);}return ok;}
 function nsURI(){return 'http://www.w3.org/2000/svg';}
 function point(e){const svg=container.querySelector('svg'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
 function nearest(e,lyric=false){const cursor=point(e),ps=[...layout(getScore(),lyric?drag.verse:0).positions.values()].filter(p=>!lyric||drag.type==='timed'||p.n.degree);return ps.reduce((best,p)=>{const y=p.y+(lyric?62+(drag.verse-1)*26:0),distance=Math.abs(y-cursor.y)*5+Math.abs(p.x-cursor.x);return !best||distance<best.distance?{p,distance}:best;},null)?.p;}
 container.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('input'))return;const bar=e.target.closest('[data-barline]'),lyric=e.target.closest('[data-lyric]'),timed=e.target.closest('[data-timed-lyric]');if(!bar&&!lyric&&!timed)return;if(!flush())return;if(timed){selectedCharacter=timed.dataset.timedLyric;container.querySelectorAll('.selected-lyric').forEach(g=>g.classList.remove('selected-lyric'));timed.classList.add('selected-lyric');}const p=lyric?layout(getScore()).positions.get(lyric.dataset.lyric):null;drag={type:bar?'bar':timed?'timed':'lyric',timedId:timed?.dataset.timedLyric,index:bar?+bar.dataset.barline:null,id:lyric?.dataset.lyric,verse:+(lyric?.dataset.verse||timed?.dataset.verse||1),charIndex:+(e.target.closest('[data-lyric-char]')?.dataset.lyricChar||0),scope:e.altKey?'single':field('lyric-scope').value,rowIds:p?[...layout(getScore()).positions.values()].filter(n=>n.row===p.row).map(n=>n.n.id):[],pointer:e.pointerId,x:e.clientX,y:e.clientY,moved:false,target:null};e.preventDefault();container.setPointerCapture(e.pointerId);});
 container.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5)return;drag.moved=true;const p=nearest(e,drag.type==='lyric'||drag.type==='timed');if(!p)return;drag.target=p.n.id;drag.offsetX=point(e).x-p.x;const svg=container.querySelector('svg');svg.querySelector('.barline-drag-preview')?.remove();const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.classList.add('barline-drag-preview');line.setAttribute('x1',p.x-17);line.setAttribute('x2',p.x-17);line.setAttribute('y1',p.y-35);line.setAttribute('y2',p.y+(drag.type==='lyric'?90:40));svg.append(line);if(drag.type==='timed'){svg.querySelector('.lyric-drag-ghost')?.remove();const ghost=document.createElementNS(nsURI(),'text'),pos=point(e);ghost.classList.add('lyric-drag-ghost');ghost.setAttribute('x',pos.x);ghost.setAttribute('y',pos.y);ghost.setAttribute('pointer-events','none');ghost.setAttribute('font-size','22');ghost.setAttribute('fill','#416d63');ghost.textContent=getScore().lyricAlignment.characters.find(c=>c.id===drag.timedId)?.text||'';svg.append(ghost);}});
 container.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(container.hasPointerCapture(e.pointerId))container.releasePointerCapture(e.pointerId);if(d.moved){suppress=true;if(d.target)commit(s=>{if(d.type==='bar'){boundary=moveBarline(s,d.index,d.target);active=boundary;}else if(d.type==='timed')moveAlignedCharacter(s,d.timedId,d.target,d.offsetX);else relocateLyricTail(s,d.id,d.verse,d.target,d.rowIds,d.scope,d.charIndex);},d.type==='bar'?'已移动小节线，保留全部音符和歌词':d.type==='timed'?'已移动这个字，其他字位置保留':'已移动歌词，目标位置的文字向后让位');else draw();}else if(d.type==='timed'){suppress=true;openTimedLyric(d.timedId);}else if(d.type==='lyric'){suppress=true;openLyric(d.id,d.verse);}else if(d.type==='bar'){boundary=d.index;selected=null;active=boundary;draw();focus();}});
 container.addEventListener('pointercancel',()=>{drag=null;draw();});container.addEventListener('dragstart',e=>e.preventDefault());
 return {draw,flush,setMode,reset(){inline=null;selected=boundary=null;range=[];anchor=null;active=0;undo=[];redo=[];draw();},snapshot:()=>({selected,active,mode}),restore(s={}){inline=null;range=[];anchor=null;selected=s.selected||null;active=s.active||0;boundary=null;mode=['select','write','lyrics','bars'].includes(s.mode)?s.mode:'select';undo=[];redo=[];draw();},markAtSelected(){const e=find(selected);return e?.n.gridTimeStart??e?.n.sourceTime;}};
}
