import {mergeScoreImagePages} from './score-image-merge.js';
import {buildImageScore} from './score-image-build.js';
import {parseScoreImage,auditImageMeasures} from './score-image-parse.js';
const $=id=>document.getElementById(id),origin=location.origin;
const state={pages:[],activePage:0,draft:null,observations:[]};
const drop=$('dropzone'),work=$('work'),fileInput=$('file'),preview=$('previewImage'),canvas=$('canvas');
const keys=['C','C#','Db','D','D#','Eb','E','F','F#','Gb','G','G#','Ab','A','A#','Bb','B'];
for(const k of keys){const o=document.createElement('option');o.value=k;o.textContent=k.replace('#','♯').replace('b','♭');$('key').append(o);} 
function invalidateDraft(){state.draft=null;$('editor').hidden=true;$('import').disabled=false;}
function addFiles(files){const incoming=[...files];if(!incoming.length)return;hideError();let added=0;for(const file of incoming){if(!file.type.startsWith('image/')){showError(`“${file.name}”不是支持的图片。PDF 请先转成图片。`);continue;}if(file.size>24*1024*1024){showError(`“${file.name}”超过 24 MB，已跳过。`);continue;}if(state.pages.length>=20){showError('一次最多识别 20 张图。');break;}if(state.pages.reduce((sum,p)=>sum+p.file.size,0)+file.size>100*1024*1024){showError('图片总大小不能超过 100 MB。');break;}state.pages.push({id:crypto.randomUUID(),file,url:URL.createObjectURL(file),image:null});added++;}if(!added)return;work.hidden=false;drop.hidden=true;state.activePage=state.pages.length-added;invalidateDraft();renderPageList();loadActivePage();$('recognize').disabled=false;$('status').textContent=`共 ${state.pages.length} 张图片，顺序可在左侧调整。`;$('recognize').textContent=`识别全部 ${state.pages.length} 张图片`;}
async function drawPage(page){if(!page.image){page.image=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error(`“${page.file.name}”无法解码`));image.src=page.url;});if(page.image.naturalWidth*page.image.naturalHeight>50_000_000)throw Error(`“${page.file.name}”像素过大，请先缩小到 5000 万像素以内。`);}canvas.width=page.image.naturalWidth;canvas.height=page.image.naturalHeight;canvas.getContext('2d',{willReadFrequently:true}).drawImage(page.image,0,0);}
async function loadActivePage(){const page=state.pages[state.activePage];if(!page)return;try{await drawPage(page);preview.src=page.url;$('previewTitle').textContent=`原图 · 第 ${state.activePage+1} / ${state.pages.length} 张`;$('previewDescription').textContent=page.file.name;renderPageList();}catch(e){showError(e.message);}}
function renderPageList(){const list=$('pageList');list.replaceChildren();state.pages.forEach((p,i)=>{const row=document.createElement('div');row.className='page-item';row.setAttribute('aria-current',String(i===state.activePage));const image=document.createElement('img');image.src=p.url;image.alt='';const name=document.createElement('span');name.className='page-name';name.textContent=`${i+1}. ${p.file.name}`;const actions=document.createElement('div');actions.className='page-actions';for(const [label,title,delta] of [['↑','上移',-1],['↓','下移',1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=title;b.disabled=i+delta<0||i+delta>=state.pages.length;b.onclick=()=>{[state.pages[i],state.pages[i+delta]]=[state.pages[i+delta],state.pages[i]];state.activePage=i+delta;invalidateDraft();renderPageList();loadActivePage();$('status').textContent='图片顺序已改变，请重新识别全部图片。';};actions.append(b);}const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title='移除此图片';remove.onclick=()=>{URL.revokeObjectURL(p.url);state.pages.splice(i,1);if(!state.pages.length){resetAll();return;}state.activePage=Math.min(i,state.pages.length-1);invalidateDraft();renderPageList();loadActivePage();$('recognize').textContent=`识别全部 ${state.pages.length} 张图片`;$('status').textContent='图片列表已改变，请重新识别。';};actions.append(remove);row.append(image,name,actions);row.onclick=e=>{if(e.target.closest('button'))return;state.activePage=i;loadActivePage();};list.append(row);});}
function resetAll(){for(const p of state.pages)URL.revokeObjectURL(p.url);state.pages=[];state.activePage=0;state.draft=null;work.hidden=true;drop.hidden=false;$('recognize').textContent='识别全部图片';}
function showError(s){$('error').textContent=s;$('error').hidden=false;}function hideError(){$('error').hidden=true;}
$('chooseImage').onclick=()=>fileInput.click();$('addImages').onclick=()=>fileInput.click();fileInput.onchange=()=>{addFiles(fileInput.files);fileInput.value='';};
for(const name of ['dragenter','dragover'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('drag');});for(const name of ['dragleave','drop'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('drag');});drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
window.addEventListener('paste',e=>{const images=[...(e.clipboardData?.items||[])].filter(i=>i.type.startsWith('image/'));if(images.length){e.preventDefault();addFiles(images.map(i=>i.getAsFile()));}});
function parseImage(result){return parseScoreImage(result,canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height));}
const select=(value,opts)=>`<select>${opts.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select>`;
function renderAudit(){const d=state.draft;if(!d)return;const box=$('measureAudit');box.replaceChildren();const items=auditImageMeasures(d.notes,$('meter').value),invalid=items.filter(item=>!item.valid);if(invalid.length){const summary=document.createElement('strong');summary.className='warning';summary.textContent=`识谱尚未完成：${invalid.length} 个小节拍数不符（第 ${invalid.map(x=>x.measure).join('、')} 小节）。请对照原图补正，导入后这些小节仍会标出。`;box.append(summary);}for(const warning of d.warnings||[]){const el=document.createElement('span');el.className='warning';el.textContent=warning;box.append(el);}for(const item of items){const el=document.createElement('span');el.className=`measure${item.valid?'':' invalid'}`;el.textContent=`第 ${item.measure} 小节 ${item.beats}/${item.expected} 拍`;box.append(el);}}
function renderDraft(){const d=state.draft;$('title').value=d.title;$('key').value=d.key;$('meter').value=['2/4','3/4','4/4','6/8'].includes(d.meter)?d.meter:'4/4';$('notes').replaceChildren();d.notes.forEach((n,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td class="num">${i+1}</td><td class="edit-cell"><button class="page-ref" type="button">第 ${(n.pageIndex??0)+1} 页</button></td><td class="edit-cell measure-cell"><input type="number" min="1" max="1000" value="${n.measure}" aria-label="第${i+1}个音符所在小节"></td><td class="edit-cell">${select(n.hold?'hold':n.degree,[['hold','延音 —'],...Array.from({length:8},(_,j)=>[j,String(j)])])}</td><td class="edit-cell">${select(n.accidental,[[0,'无'],[1,'♯'],[-1,'♭']])}</td><td class="edit-cell">${select(n.octave,[[-2,'低低音'],[-1,'低音'],[0,'中音'],[1,'高音'],[2,'高高音']])}</td><td class="edit-cell">${select(n.base,[[1,'全音'],[2,'二分'],[4,'四分'],[8,'八分'],[16,'十六分']])}</td><td class="edit-cell">${select(n.dots,[[0,'无'],[1,'附点']])}</td><td class="edit-cell lyric-cell"><input value="${escapeHtml(n.lyric)}" aria-label="对应歌词" placeholder="单字歌词"></td>`;$('notes').append(tr);tr.querySelector('.page-ref').onclick=()=>{state.activePage=n.pageIndex??0;loadActivePage();};const controls=tr.querySelectorAll('input,select');const [measure,degree,acc,oct,base,dots,lyric]=controls;measure.oninput=()=>{n.measure=Math.max(1,Number(measure.value)||1);renderAudit();};degree.onchange=()=>{n.hold=degree.value==='hold';if(!n.hold)n.degree=Number(degree.value);renderAudit();};acc.onchange=()=>n.accidental=Number(acc.value);oct.onchange=()=>n.octave=Number(oct.value);base.onchange=()=>{n.base=Number(base.value);renderAudit();};dots.onchange=()=>{n.dots=Number(dots.value);renderAudit();};lyric.oninput=()=>n.lyric=lyric.value;});renderChords();renderAudit();$('meter').onchange=renderAudit;$('raw').textContent=d.lines.map(x=>x.text).join('\n');$('editor').hidden=false;$('status').textContent=`初稿：${d.notes.length} 个音符候选，${d.chords.length} 个和弦候选。每项请对照原图。`;$('title').oninput=()=>d.title=$('title').value;$('key').onchange=()=>d.key=$('key').value;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderChords(){const box=$('chords');box.replaceChildren();state.draft.chords.forEach((c,i)=>{const row=document.createElement('div');row.className='chord-row';row.innerHTML=`<input type="number" min="1" max="1000" value="${c.measure}" aria-label="和弦小节"><input value="${escapeHtml(c.label)}" aria-label="和弦名称"><button type="button" aria-label="删除和弦">×</button>`;const [m,l,del]=row.children;m.oninput=()=>c.measure=Math.max(1,Number(m.value)||1);l.oninput=()=>c.label=l.value;del.onclick=()=>{state.draft.chords.splice(i,1);renderChords();};box.append(row);});}
$('addChord').onclick=()=>{state.draft?.chords.push({measure:1,label:'C'});renderChords();};$('recognize').onclick=async()=>{if(!state.pages.length)return;hideError();invalidateDraft();$('recognize').disabled=true;const pageDrafts=[];try{for(let i=0;i<state.pages.length;i++){const page=state.pages[i];$('status').textContent=`正在识别第 ${i+1} / ${state.pages.length} 张图片…`;await drawPage(page);const response=await fetch('/api/score-image/recognize',{method:'POST',headers:{'Content-Type':page.file.type},body:page.file});const result=await response.json();if(!response.ok)throw Error(`第 ${i+1} 张：${result.error||'识别失败'}`);try{pageDrafts.push(parseImage(result));}catch(error){state.activePage=i;await loadActivePage();throw Error(`第 ${i+1} 张“${page.file.name}”：${error.message}`);}}
 state.draft=mergeScoreImagePages(pageDrafts);renderDraft();$('status').textContent=`已按顺序合并 ${state.pages.length} 张图片：${state.draft.notes.length} 个音符候选、${state.draft.chords.length} 个和弦候选。请逐项对照原图。`;
 }catch(e){showError(e.message);$('status').textContent='识别没有完成';}finally{$('recognize').disabled=false;};};
function buildScore(){return buildImageScore(state.draft,{title:$('title').value,key:$('key').value,meter:$('meter').value});}
$('import').onclick=()=>{hideError();try{const score=buildScore();$('import').disabled=true;$('status').textContent='正在保存图片识谱结果到工程…';parent.postMessage({type:'workspace:import-score',score},origin);}catch(e){showError(e.message);}};$('cancel').onclick=resetAll;
window.addEventListener('message',e=>{if(e.origin!==origin||e.source!==parent||e.data?.type!=='score-image:error')return;showError(e.data.message);$('import').disabled=false;$('status').textContent='导入失败';});
parent.postMessage({type:'workspace:ready'},origin);
